<?php

/*
| Vitrin ve Product schema için teknik özellik adı eşlemesi.
| Anahtarlar küçük harf (Türkçe) ham addır; değer vitrinde gösterilen standart addır.
| Birim taşıyan adlar (kW / HP / mSS / m³/h) birimi korunarak eşlenir; aynı üründe
| iki farklı birim yan yana durabildiği için birimler tek ada indirgenmez.
| Veritabanındaki ham anahtarlar değişmez (pompa seçici ve pazaryeri eşlemeleri onları kullanır).
*/

return [

    'aliases' => [
        // Motor gücü
        'motor gücü' => 'Motor Gücü',
        'güç' => 'Motor Gücü',
        'pompa gücü' => 'Motor Gücü',
        'güç (kw)' => 'Motor Gücü (kW)',
        'kw' => 'Motor Gücü (kW)',
        'motor gücü (kw)' => 'Motor Gücü (kW)',
        'güç (hp)' => 'Motor Gücü (HP)',
        'hp' => 'Motor Gücü (HP)',
        'motor gücü (hp)' => 'Motor Gücü (HP)',
        'pompa gücü (hp)' => 'Motor Gücü (HP)',

        // Voltaj
        'voltaj' => 'Voltaj',
        'elektrik' => 'Voltaj',
        'elektrik (voltaj)' => 'Voltaj',
        'elektrik voltajı' => 'Voltaj',
        'çalışma voltajı' => 'Voltaj',
        'giriş voltajı' => 'Voltaj',
        'gerilim' => 'Voltaj',
        'besleme' => 'Voltaj',
        'besleme gerilimi' => 'Voltaj',
        'voltage' => 'Voltaj',
        'volta' => 'Voltaj',
        'voltaj (v)' => 'Voltaj (V)',
        'elektrik (volt)' => 'Voltaj (V)',

        // Frekans
        'frekans' => 'Frekans',
        'frekans (hz)' => 'Frekans (Hz)',
        'hz' => 'Frekans (Hz)',

        // Akım
        'akım' => 'Akım',
        'amper' => 'Akım',
        'ampere' => 'Akım',
        'akım (a)' => 'Akım (A)',
        'a (akım)' => 'Akım (A)',

        // Debi
        'debi' => 'Debi',
        'sıvı debisi' => 'Debi',
        'su basma kapasitesi' => 'Debi',
        'debi miktarı' => 'Debi',
        'debi kapasitesi' => 'Debi',
        'debi (m³/h)' => 'Debi (m³/h)',
        'debi (m3/h)' => 'Debi (m³/h)',
        'sıvı debisi (m³/h)' => 'Debi (m³/h)',
        'debi q (m³/h)' => 'Debi (m³/h)',
        'su basma kapasitesi (m³/h)' => 'Debi (m³/h)',
        'max. debi' => 'Maks. Debi',
        'max debi' => 'Maks. Debi',
        'maks. debi' => 'Maks. Debi',
        'maksimum debi' => 'Maks. Debi',
        'maximum su debisi' => 'Maks. Debi',
        'max. su aktarma debisi' => 'Maks. Debi',
        'maksimum su basma kapasitesi' => 'Maks. Debi',
        'maks. su basma kapasitesi' => 'Maks. Debi',
        'max. debi (m³/h)' => 'Maks. Debi (m³/h)',
        'max. debi (m3/h)' => 'Maks. Debi (m³/h)',
        'max. debi m3/h' => 'Maks. Debi (m³/h)',
        'max. debi m³/h' => 'Maks. Debi (m³/h)',
        'max debi (m³/h)' => 'Maks. Debi (m³/h)',
        'max debi (m3/h)' => 'Maks. Debi (m³/h)',
        'maks. debi (m³/h)' => 'Maks. Debi (m³/h)',
        'maks. debi (m3/h)' => 'Maks. Debi (m³/h)',
        'maks. debi m3/h' => 'Maks. Debi (m³/h)',
        'maks. debi m³/h' => 'Maks. Debi (m³/h)',
        'maksimum debi (m³/h)' => 'Maks. Debi (m³/h)',
        'maksimum debi (m3/h)' => 'Maks. Debi (m³/h)',
        'q max (m³/h)' => 'Maks. Debi (m³/h)',

        // Basma yüksekliği
        'basma yüksekliği' => 'Basma Yüksekliği',
        'basma yüksekliği (mss)' => 'Basma Yüksekliği (mSS)',
        'basma yüksekliği (m)' => 'Basma Yüksekliği (m)',
        'basma h (m)' => 'Basma Yüksekliği (m)',
        'max. yükseklik' => 'Maks. Basma Yüksekliği',
        'max yükseklik' => 'Maks. Basma Yüksekliği',
        'maks. yükseklik' => 'Maks. Basma Yüksekliği',
        'maksimum yükseklik' => 'Maks. Basma Yüksekliği',
        'maks. basma yüksekliği' => 'Maks. Basma Yüksekliği',
        'max. basma yüksekliği' => 'Maks. Basma Yüksekliği',
        'max basma yüksekliği' => 'Maks. Basma Yüksekliği',
        'maksimum basma yüksekliği' => 'Maks. Basma Yüksekliği',
        'max. yükseklik (mss)' => 'Maks. Basma Yüksekliği (mSS)',
        'max. yükseklik mss' => 'Maks. Basma Yüksekliği (mSS)',
        'max yükseklik (mss)' => 'Maks. Basma Yüksekliği (mSS)',
        'maks. yükseklik (mss)' => 'Maks. Basma Yüksekliği (mSS)',
        'maks. yükseklik mss' => 'Maks. Basma Yüksekliği (mSS)',
        'maksimum yükseklik (mss)' => 'Maks. Basma Yüksekliği (mSS)',
        'maks. basma yüksekliği (mss)' => 'Maks. Basma Yüksekliği (mSS)',
        'maksimum basma yüksekliği (mss)' => 'Maks. Basma Yüksekliği (mSS)',
        'h max (mss)' => 'Maks. Basma Yüksekliği (mSS)',
        'max. yükseklik (m)' => 'Maks. Basma Yüksekliği (m)',
        'maks. yükseklik (m)' => 'Maks. Basma Yüksekliği (m)',
        'max. basma yüksekliği (m)' => 'Maks. Basma Yüksekliği (m)',
        'maksimum basma yüksekliği (m)' => 'Maks. Basma Yüksekliği (m)',

        // Bağlantı ölçüleri
        'çıkış ölçüsü' => 'Çıkış Ölçüsü',
        'çıkış çapı' => 'Çıkış Ölçüsü',
        'çıkış bağlantı çapı' => 'Çıkış Ölçüsü',
        'çıkış bağlantısı' => 'Çıkış Ölçüsü',
        'çıkış boyutu' => 'Çıkış Ölçüsü',
        'çıkış' => 'Çıkış Ölçüsü',
        'pompa çıkışı' => 'Çıkış Ölçüsü',
        'basma çıkış çapı' => 'Çıkış Ölçüsü',
        'çıkış bağlantı çapı (inç)' => 'Çıkış Ölçüsü (inç)',
        'giriş ölçüsü' => 'Giriş Ölçüsü',
        'giriş bağlantısı' => 'Giriş Ölçüsü',
        'giriş bağlantı çapı' => 'Giriş Ölçüsü',
        'giriş' => 'Giriş Ölçüsü',
        'giriş/çıkış' => 'Giriş / Çıkış Ölçüsü',
        'giriş / çıkış' => 'Giriş / Çıkış Ölçüsü',
        'giriş çıkış' => 'Giriş / Çıkış Ölçüsü',
        'giriş/çıkış ölçüsü' => 'Giriş / Çıkış Ölçüsü',
        'giriş / çıkış ölçüsü' => 'Giriş / Çıkış Ölçüsü',
        'giriş çıkış ölçüsü' => 'Giriş / Çıkış Ölçüsü',
        'giriş/çıkış ölçüleri' => 'Giriş / Çıkış Ölçüsü',
        'giriş/çıkış çapları' => 'Giriş / Çıkış Ölçüsü',
        'giriş/çıkış çapı' => 'Giriş / Çıkış Ölçüsü',
        'giriş/çıkış bağlantısı' => 'Giriş / Çıkış Ölçüsü',
        'giriş/çıkış boyutları' => 'Giriş / Çıkış Ölçüsü',
        'pompa giriş/çıkış' => 'Giriş / Çıkış Ölçüsü',
        'emme/basma ağzı' => 'Giriş / Çıkış Ölçüsü',
        'emme / basma ağzı' => 'Giriş / Çıkış Ölçüsü',

        // Emiş / daldırma / çalışma derinliği
        'emiş derinliği' => 'Emiş Derinliği',
        'emme derinliği' => 'Emiş Derinliği',
        'maks. emiş derinliği' => 'Maks. Emiş Derinliği',
        'max. emiş derinliği' => 'Maks. Emiş Derinliği',
        'max emiş derinliği' => 'Maks. Emiş Derinliği',
        'maksimum emiş derinliği' => 'Maks. Emiş Derinliği',
        'maksimum emiş' => 'Maks. Emiş Derinliği',
        'daldırma derinliği' => 'Daldırma Derinliği',
        'daldırma derinliği (m)' => 'Daldırma Derinliği (m)',
        'maks. daldırma derinliği' => 'Maks. Daldırma Derinliği',
        'max. daldırma derinliği' => 'Maks. Daldırma Derinliği',
        'maksimum daldırma derinliği' => 'Maks. Daldırma Derinliği',
        'çalışma derinliği' => 'Çalışma Derinliği',
        'max çalışma derinliği' => 'Maks. Çalışma Derinliği',
        'max. çalışma derinliği' => 'Maks. Çalışma Derinliği',
        'maks. çalışma derinliği' => 'Maks. Çalışma Derinliği',
        'maksimum çalışma derinliği' => 'Maks. Çalışma Derinliği',

        // Devir
        'devir' => 'Devir',
        'devir sayısı' => 'Devir',
        'devir hızı' => 'Devir',
        'dakikada devir' => 'Devir',
        'dönüş hızı' => 'Devir',
        'dönme hızı' => 'Devir',
        'motor devir hızı' => 'Devir',
        'motor devir sayısı' => 'Devir',
        'devir (d/d)' => 'Devir (d/d)',
        'devir d/d' => 'Devir (d/d)',
        'devir/d/d' => 'Devir (d/d)',
        'devir/dakika' => 'Devir (d/d)',
        'dönüş hızı (d/d)' => 'Devir (d/d)',
        'devir (rpm)' => 'Devir (d/d)',

        // Sıcaklık
        'sıvı basma sıcaklığı' => 'Sıvı Sıcaklığı',
        'sıvı çalışma sıcaklığı' => 'Sıvı Sıcaklığı',
        'sıvı sıcaklığı dayanımı' => 'Sıvı Sıcaklığı',
        'akışkan sıcaklığı' => 'Sıvı Sıcaklığı',
        'maks. sıvı sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'max sıvı sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'maksimum sıvı sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'maks. sıvı basma sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'max. sıvı basma sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'maksimum sıvı basma sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'maks. akışkan sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'max. akışkan sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'maks. su sıcaklığı' => 'Maks. Sıvı Sıcaklığı',
        'ortam sıcaklığı' => 'Ortam Sıcaklığı',
        'ortam sıcaklığı dayanımı' => 'Ortam Sıcaklığı',

        // Basınç
        'maksimum basınç' => 'Maks. Basınç',
        'maks. basınç' => 'Maks. Basınç',
        'max. basınç' => 'Maks. Basınç',
        'max basınç' => 'Maks. Basınç',
        'maks. basınç (mss)' => 'Maks. Basınç (mSS)',
        'max. basınç (mss)' => 'Maks. Basınç (mSS)',
        'max. bar basıncı' => 'Maks. Basınç (bar)',
        'max bar basıncı' => 'Maks. Basınç (bar)',
        'maksimum bar basıncı' => 'Maks. Basınç (bar)',

        // Ölçü ve ağırlık
        'pompa dış çapı' => 'Pompa Dış Çapı',
        'pompa dışı çapı' => 'Pompa Dış Çapı',
        'dış çap' => 'Pompa Dış Çapı',
        'pompa dış çapı (mm)' => 'Pompa Dış Çapı (mm)',
        'ağırlık' => 'Ağırlık',
        'ağırlık (kg)' => 'Ağırlık (kg)',

        // Kablo
        'kablo uzunluğu' => 'Kablo Uzunluğu',
        'elektrik kablo uzunluğu' => 'Kablo Uzunluğu',
        'elektrik kablosu uzunluğu' => 'Kablo Uzunluğu',
        'fişli kablo uzunluğu' => 'Kablo Uzunluğu',
        'kablo uzunluğu (m)' => 'Kablo Uzunluğu (m)',

        // Malzeme
        'gövde malzemesi' => 'Gövde Malzemesi',
        'pompa gövdesi' => 'Gövde Malzemesi',
        'gövde' => 'Gövde Malzemesi',
        'gövdesi' => 'Gövde Malzemesi',
        'gövde materyali' => 'Gövde Malzemesi',
        'malzeme gövdesi' => 'Gövde Malzemesi',
        'çark malzemesi' => 'Çark Malzemesi',
        'çark' => 'Çark Malzemesi',
        'çark materyali' => 'Çark Malzemesi',
        'pompa çarkı' => 'Çark Malzemesi',
        'mil malzemesi' => 'Mil Malzemesi',
        'mil' => 'Mil Malzemesi',
        'mili' => 'Mil Malzemesi',
        'motor mili' => 'Mil Malzemesi',
        'pompa mili' => 'Mil Malzemesi',
        'pompa mil' => 'Mil Malzemesi',
        'mili malzemesi' => 'Mil Malzemesi',
        'motor mili malzemesi' => 'Mil Malzemesi',

        // Partikül geçişi
        'geçebilecek parçacık boyutu' => 'Geçebilecek Parçacık Boyutu',
        'geçebileceği parçacık boyutu' => 'Geçebilecek Parçacık Boyutu',
        'geçebilen parça boyutu' => 'Geçebilecek Parçacık Boyutu',
        'parça geçirgenliği' => 'Geçebilecek Parçacık Boyutu',
        'partikül geçirgenliği' => 'Geçebilecek Parçacık Boyutu',
        'geçirgenlik' => 'Geçebilecek Parçacık Boyutu',
        'maks. partikül çapı' => 'Maks. Partikül Çapı',
        'max partikül çapı' => 'Maks. Partikül Çapı',
        'max. partikül çapı' => 'Maks. Partikül Çapı',
        'maksimum partikül çapı' => 'Maks. Partikül Çapı',
        'partikül aktarım çapı' => 'Maks. Partikül Çapı',
        'maks. partikül aktarım çapı' => 'Maks. Partikül Çapı',
        'maksimum partikül aktarım çapı' => 'Maks. Partikül Çapı',
        'max. partikül çapı (mm)' => 'Maks. Partikül Çapı (mm)',

        // Diğer
        'tank hacmi' => 'Tank Hacmi',
        'tank kapasitesi' => 'Tank Hacmi',
        'depo hacmi' => 'Tank Hacmi',
        'garanti' => 'Garanti',
        'garanti süresi' => 'Garanti',
        'sızdırmazlık' => 'Sızdırmazlık',
        'sızdırmazlık tipi' => 'Sızdırmazlık',
        'sızdırmazlık sistemi' => 'Sızdırmazlık',
        'kullanım alanı' => 'Kullanım Alanı',
        'kullanım alanları' => 'Kullanım Alanı',
        'model' => 'Model',
        'modeli' => 'Model',
        'tip' => 'Tip',
        'tipi' => 'Tip',
    ],

    // İçe aktarılan tabloların başlık satırı ("Teknik Özellikler | Değerler"); veri değildir.
    'header_labels' => [
        'teknik özellikler',
        'teknik özellik',
        'teknik veriler',
        'özellikler',
        'özellik',
    ],

    'header_values' => [
        'değerler',
        'değerleri',
        'değer',
        'değer / açıklama',
        'detaylar',
        'açıklama',
    ],

    // Model tablolarının sütun başlığı ("Tip | kW", "Tip | Hacim (lt)"): değer başka bir özelliğin adıdır.
    'column_header_labels' => [
        'tip',
        'tipi',
        'model',
    ],

    'column_header_values' => [
        'hacim (lt)',
    ],

];
