<?php

return array (
  'cities' => 
  array (
    'ADANA' => 
    array (
      0 => 'ALADAĞ',
      1 => 'CEYHAN',
      2 => 'ÇUKUROVA',
      3 => 'FEKE',
      4 => 'İMAMOĞLU',
      5 => 'KARAİSALI',
      6 => 'KARATAŞ',
      7 => 'KOZAN',
      8 => 'POZANTI',
      9 => 'SAİMBEYLİ',
      10 => 'SARIÇAM',
      11 => 'SEYHAN',
      12 => 'TUFANBEYLİ',
      13 => 'YUMURTALIK',
      14 => 'YÜREĞİR',
    ),
    'ADIYAMAN' => 
    array (
      0 => 'BESNİ',
      1 => 'ÇELİKHAN',
      2 => 'GERGER',
      3 => 'GÖLBAŞI',
      4 => 'KAHTA',
      5 => 'MERKEZ',
      6 => 'SAMSAT',
      7 => 'SİNCİK',
      8 => 'TUT',
    ),
    'AFYONKARAHİSAR' => 
    array (
      0 => 'BAŞMAKÇI',
      1 => 'BAYAT',
      2 => 'BOLVADİN',
      3 => 'ÇAY',
      4 => 'ÇOBANLAR',
      5 => 'DAZKIRI',
      6 => 'DİNAR',
      7 => 'EMİRDAĞ',
      8 => 'EVCİLER',
      9 => 'HOCALAR',
      10 => 'İHSANİYE',
      11 => 'İSCEHİSAR',
      12 => 'KIZILÖREN',
      13 => 'MERKEZ',
      14 => 'SANDIKLI',
      15 => 'SİNANPAŞA',
      16 => 'SULTANDAĞI',
      17 => 'ŞUHUT',
    ),
    'AĞRI' => 
    array (
      0 => 'DİYADİN',
      1 => 'DOĞUBAYAZIT',
      2 => 'ELEŞKİRT',
      3 => 'HAMUR',
      4 => 'MERKEZ',
      5 => 'PATNOS',
      6 => 'TAŞLIÇAY',
      7 => 'TUTAK',
    ),
    'AKSARAY' => 
    array (
      0 => 'AĞAÇÖREN',
      1 => 'ESKİL',
      2 => 'GÜLAĞAÇ',
      3 => 'GÜZELYURT',
      4 => 'MERKEZ',
      5 => 'ORTAKÖY',
      6 => 'SARIYAHŞİ',
      7 => 'SULTANHANI',
    ),
    'AMASYA' => 
    array (
      0 => 'GÖYNÜCEK',
      1 => 'GÜMÜŞHACIKÖY',
      2 => 'HAMAMÖZÜ',
      3 => 'MERKEZ',
      4 => 'MERZİFON',
      5 => 'SULUOVA',
      6 => 'TAŞOVA',
    ),
    'ANKARA' => 
    array (
      0 => 'AKYURT',
      1 => 'ALTINDAĞ',
      2 => 'AYAŞ',
      3 => 'BALA',
      4 => 'BEYPAZARI',
      5 => 'ÇAMLIDERE',
      6 => 'ÇANKAYA',
      7 => 'ÇUBUK',
      8 => 'ELMADAĞ',
      9 => 'ETİMESGUT',
      10 => 'EVREN',
      11 => 'GÖLBAŞI',
      12 => 'GÜDÜL',
      13 => 'HAYMANA',
      14 => 'KAHRAMANKAZAN',
      15 => 'KALECİK',
      16 => 'KEÇİÖREN',
      17 => 'KIZILCAHAMAM',
      18 => 'MAMAK',
      19 => 'NALLIHAN',
      20 => 'POLATLI',
      21 => 'PURSAKLAR',
      22 => 'SİNCAN',
      23 => 'ŞEREFLİKOÇHİSAR',
      24 => 'YENİMAHALLE',
    ),
    'ANTALYA' => 
    array (
      0 => 'AKSEKİ',
      1 => 'AKSU',
      2 => 'ALANYA',
      3 => 'DEMRE',
      4 => 'DÖŞEMEALTI',
      5 => 'ELMALI',
      6 => 'FİNİKE',
      7 => 'GAZİPAŞA',
      8 => 'GÜNDOĞMUŞ',
      9 => 'İBRADI',
      10 => 'KAŞ',
      11 => 'KEMER',
      12 => 'KEPEZ',
      13 => 'KONYAALTI',
      14 => 'KORKUTELİ',
      15 => 'KUMLUCA',
      16 => 'MANAVGAT',
      17 => 'MURATPAŞA',
      18 => 'SERİK',
    ),
    'ARDAHAN' => 
    array (
      0 => 'ÇILDIR',
      1 => 'DAMAL',
      2 => 'GÖLE',
      3 => 'HANAK',
      4 => 'MERKEZ',
      5 => 'POSOF',
    ),
    'ARTVİN' => 
    array (
      0 => 'ARDANUÇ',
      1 => 'ARHAVİ',
      2 => 'BORÇKA',
      3 => 'HOPA',
      4 => 'KEMALPAŞA',
      5 => 'MERKEZ',
      6 => 'MURGUL',
      7 => 'ŞAVŞAT',
      8 => 'YUSUFELİ',
    ),
    'AYDIN' => 
    array (
      0 => 'BOZDOĞAN',
      1 => 'BUHARKENT',
      2 => 'ÇİNE',
      3 => 'DİDİM',
      4 => 'EFELER',
      5 => 'GERMENCİK',
      6 => 'İNCİRLİOVA',
      7 => 'KARACASU',
      8 => 'KARPUZLU',
      9 => 'KOÇARLI',
      10 => 'KÖŞK',
      11 => 'KUŞADASI',
      12 => 'KUYUCAK',
      13 => 'NAZİLLİ',
      14 => 'SÖKE',
      15 => 'SULTANHİSAR',
      16 => 'YENİPAZAR',
    ),
    'BALIKESİR' => 
    array (
      0 => 'ALTIEYLÜL',
      1 => 'AYVALIK',
      2 => 'BALYA',
      3 => 'BANDIRMA',
      4 => 'BİGADİÇ',
      5 => 'BURHANİYE',
      6 => 'DURSUNBEY',
      7 => 'EDREMİT',
      8 => 'ERDEK',
      9 => 'GÖMEÇ',
      10 => 'GÖNEN',
      11 => 'HAVRAN',
      12 => 'İVRİNDİ',
      13 => 'KARESİ',
      14 => 'KEPSUT',
      15 => 'MANYAS',
      16 => 'MARMARA',
      17 => 'SAVAŞTEPE',
      18 => 'SINDIRGI',
      19 => 'SUSURLUK',
    ),
    'BARTIN' => 
    array (
      0 => 'AMASRA',
      1 => 'KURUCAŞİLE',
      2 => 'MERKEZ',
      3 => 'ULUS',
    ),
    'BATMAN' => 
    array (
      0 => 'BEŞİRİ',
      1 => 'GERCÜŞ',
      2 => 'HASANKEYF',
      3 => 'KOZLUK',
      4 => 'MERKEZ',
      5 => 'SASON',
    ),
    'BAYBURT' => 
    array (
      0 => 'AYDINTEPE',
      1 => 'DEMİRÖZÜ',
      2 => 'MERKEZ',
    ),
    'BİLECİK' => 
    array (
      0 => 'BOZÜYÜK',
      1 => 'GÖLPAZARI',
      2 => 'İNHİSAR',
      3 => 'MERKEZ',
      4 => 'OSMANELİ',
      5 => 'PAZARYERİ',
      6 => 'SÖĞÜT',
      7 => 'YENİPAZAR',
    ),
    'BİNGÖL' => 
    array (
      0 => 'ADAKLI',
      1 => 'GENÇ',
      2 => 'KARLIOVA',
      3 => 'KİĞI',
      4 => 'MERKEZ',
      5 => 'SOLHAN',
      6 => 'YAYLADERE',
      7 => 'YEDİSU',
    ),
    'BİTLİS' => 
    array (
      0 => 'ADİLCEVAZ',
      1 => 'AHLAT',
      2 => 'GÜROYMAK',
      3 => 'HİZAN',
      4 => 'MERKEZ',
      5 => 'MUTKİ',
      6 => 'TATVAN',
    ),
    'BOLU' => 
    array (
      0 => 'DÖRTDİVAN',
      1 => 'GEREDE',
      2 => 'GÖYNÜK',
      3 => 'KIBRISCIK',
      4 => 'MENGEN',
      5 => 'MERKEZ',
      6 => 'MUDURNU',
      7 => 'SEBEN',
      8 => 'YENİÇAĞA',
    ),
    'BURDUR' => 
    array (
      0 => 'AĞLASUN',
      1 => 'ALTINYAYLA',
      2 => 'BUCAK',
      3 => 'ÇAVDIR',
      4 => 'ÇELTİKÇİ',
      5 => 'GÖLHİSAR',
      6 => 'KARAMANLI',
      7 => 'KEMER',
      8 => 'MERKEZ',
      9 => 'TEFENNİ',
      10 => 'YEŞİLOVA',
    ),
    'BURSA' => 
    array (
      0 => 'BÜYÜKORHAN',
      1 => 'GEMLİK',
      2 => 'GÜRSU',
      3 => 'HARMANCIK',
      4 => 'İNEGÖL',
      5 => 'İZNİK',
      6 => 'KARACABEY',
      7 => 'KELES',
      8 => 'KESTEL',
      9 => 'MUDANYA',
      10 => 'MUSTAFAKEMALPAŞA',
      11 => 'NİLÜFER',
      12 => 'ORHANELİ',
      13 => 'ORHANGAZİ',
      14 => 'OSMANGAZİ',
      15 => 'YENİŞEHİR',
      16 => 'YILDIRIM',
    ),
    'ÇANAKKALE' => 
    array (
      0 => 'AYVACIK',
      1 => 'BAYRAMİÇ',
      2 => 'BİGA',
      3 => 'BOZCAADA',
      4 => 'ÇAN',
      5 => 'ECEABAT',
      6 => 'EZİNE',
      7 => 'GELİBOLU',
      8 => 'GÖKÇEADA',
      9 => 'LAPSEKİ',
      10 => 'MERKEZ',
      11 => 'YENİCE',
    ),
    'ÇANKIRI' => 
    array (
      0 => 'ATKARACALAR',
      1 => 'BAYRAMÖREN',
      2 => 'ÇERKEŞ',
      3 => 'ELDİVAN',
      4 => 'ILGAZ',
      5 => 'KIZILIRMAK',
      6 => 'KORGUN',
      7 => 'KURŞUNLU',
      8 => 'MERKEZ',
      9 => 'ORTA',
      10 => 'ŞABANÖZÜ',
      11 => 'YAPRAKLI',
    ),
    'ÇORUM' => 
    array (
      0 => 'ALACA',
      1 => 'BAYAT',
      2 => 'BOĞAZKALE',
      3 => 'DODURGA',
      4 => 'İSKİLİP',
      5 => 'KARGI',
      6 => 'LAÇİN',
      7 => 'MECİTÖZÜ',
      8 => 'MERKEZ',
      9 => 'OĞUZLAR',
      10 => 'ORTAKÖY',
      11 => 'OSMANCIK',
      12 => 'SUNGURLU',
      13 => 'UĞURLUDAĞ',
    ),
    'DENİZLİ' => 
    array (
      0 => 'ACIPAYAM',
      1 => 'BABADAĞ',
      2 => 'BAKLAN',
      3 => 'BEKİLLİ',
      4 => 'BEYAĞAÇ',
      5 => 'BOZKURT',
      6 => 'BULDAN',
      7 => 'ÇAL',
      8 => 'ÇAMELİ',
      9 => 'ÇARDAK',
      10 => 'ÇİVRİL',
      11 => 'GÜNEY',
      12 => 'HONAZ',
      13 => 'KALE',
      14 => 'MERKEZEFENDİ',
      15 => 'PAMUKKALE',
      16 => 'SARAYKÖY',
      17 => 'SERİNHİSAR',
      18 => 'TAVAS',
    ),
    'DİYARBAKIR' => 
    array (
      0 => 'BAĞLAR',
      1 => 'BİSMİL',
      2 => 'ÇERMİK',
      3 => 'ÇINAR',
      4 => 'ÇÜNGÜŞ',
      5 => 'DİCLE',
      6 => 'EĞİL',
      7 => 'ERGANİ',
      8 => 'HANİ',
      9 => 'HAZRO',
      10 => 'KAYAPINAR',
      11 => 'KOCAKÖY',
      12 => 'KULP',
      13 => 'LİCE',
      14 => 'SİLVAN',
      15 => 'SUR',
      16 => 'YENİŞEHİR',
    ),
    'DÜZCE' => 
    array (
      0 => 'AKÇAKOCA',
      1 => 'CUMAYERİ',
      2 => 'ÇİLİMLİ',
      3 => 'GÖLYAKA',
      4 => 'GÜMÜŞOVA',
      5 => 'KAYNAŞLI',
      6 => 'MERKEZ',
      7 => 'YIĞILCA',
    ),
    'EDİRNE' => 
    array (
      0 => 'ENEZ',
      1 => 'HAVSA',
      2 => 'İPSALA',
      3 => 'KEŞAN',
      4 => 'LALAPAŞA',
      5 => 'MERİÇ',
      6 => 'MERKEZ',
      7 => 'SÜLOĞLU',
      8 => 'UZUNKÖPRÜ',
    ),
    'ELAZIĞ' => 
    array (
      0 => 'AĞIN',
      1 => 'ALACAKAYA',
      2 => 'ARICAK',
      3 => 'BASKİL',
      4 => 'KARAKOÇAN',
      5 => 'KEBAN',
      6 => 'KOVANCILAR',
      7 => 'MADEN',
      8 => 'MERKEZ',
      9 => 'PALU',
      10 => 'SİVRİCE',
    ),
    'ERZİNCAN' => 
    array (
      0 => 'ÇAYIRLI',
      1 => 'İLİÇ',
      2 => 'KEMAH',
      3 => 'KEMALİYE',
      4 => 'MERKEZ',
      5 => 'OTLUKBELİ',
      6 => 'REFAHİYE',
      7 => 'TERCAN',
      8 => 'ÜZÜMLÜ',
    ),
    'ERZURUM' => 
    array (
      0 => 'AŞKALE',
      1 => 'AZİZİYE',
      2 => 'ÇAT',
      3 => 'HINIS',
      4 => 'HORASAN',
      5 => 'İSPİR',
      6 => 'KARAÇOBAN',
      7 => 'KARAYAZI',
      8 => 'KÖPRÜKÖY',
      9 => 'NARMAN',
      10 => 'OLTU',
      11 => 'OLUR',
      12 => 'PALANDÖKEN',
      13 => 'PASİNLER',
      14 => 'PAZARYOLU',
      15 => 'ŞENKAYA',
      16 => 'TEKMAN',
      17 => 'TORTUM',
      18 => 'UZUNDERE',
      19 => 'YAKUTİYE',
    ),
    'ESKİŞEHİR' => 
    array (
      0 => 'ALPU',
      1 => 'BEYLİKOVA',
      2 => 'ÇİFTELER',
      3 => 'GÜNYÜZÜ',
      4 => 'HAN',
      5 => 'İNÖNÜ',
      6 => 'MAHMUDİYE',
      7 => 'MİHALGAZİ',
      8 => 'MİHALIÇÇIK',
      9 => 'ODUNPAZARI',
      10 => 'SARICAKAYA',
      11 => 'SEYİTGAZİ',
      12 => 'SİVRİHİSAR',
      13 => 'TEPEBAŞI',
    ),
    'GAZİANTEP' => 
    array (
      0 => 'ARABAN',
      1 => 'İSLAHİYE',
      2 => 'KARKAMIŞ',
      3 => 'NİZİP',
      4 => 'NURDAĞI',
      5 => 'OĞUZELİ',
      6 => 'ŞAHİNBEY',
      7 => 'ŞEHİTKAMİL',
      8 => 'YAVUZELİ',
    ),
    'GİRESUN' => 
    array (
      0 => 'ALUCRA',
      1 => 'BULANCAK',
      2 => 'ÇAMOLUK',
      3 => 'ÇANAKÇI',
      4 => 'DERELİ',
      5 => 'DOĞANKENT',
      6 => 'ESPİYE',
      7 => 'EYNESİL',
      8 => 'GÖRELE',
      9 => 'GÜCE',
      10 => 'KEŞAP',
      11 => 'MERKEZ',
      12 => 'PİRAZİZ',
      13 => 'ŞEBİNKARAHİSAR',
      14 => 'TİREBOLU',
      15 => 'YAĞLIDERE',
    ),
    'GÜMÜŞHANE' => 
    array (
      0 => 'KELKİT',
      1 => 'KÖSE',
      2 => 'KÜRTÜN',
      3 => 'MERKEZ',
      4 => 'ŞİRAN',
      5 => 'TORUL',
    ),
    'HAKKARİ' => 
    array (
      0 => 'ÇUKURCA',
      1 => 'DERECİK',
      2 => 'MERKEZ',
      3 => 'ŞEMDİNLİ',
      4 => 'YÜKSEKOVA',
    ),
    'HATAY' => 
    array (
      0 => 'ALTINÖZÜ',
      1 => 'ANTAKYA',
      2 => 'ARSUZ',
      3 => 'BELEN',
      4 => 'DEFNE',
      5 => 'DÖRTYOL',
      6 => 'ERZİN',
      7 => 'HASSA',
      8 => 'İSKENDERUN',
      9 => 'KIRIKHAN',
      10 => 'KUMLU',
      11 => 'PAYAS',
      12 => 'REYHANLI',
      13 => 'SAMANDAĞ',
      14 => 'YAYLADAĞI',
    ),
    'IĞDIR' => 
    array (
      0 => 'ARALIK',
      1 => 'KARAKOYUNLU',
      2 => 'MERKEZ',
      3 => 'TUZLUCA',
    ),
    'ISPARTA' => 
    array (
      0 => 'AKSU',
      1 => 'ATABEY',
      2 => 'EĞİRDİR',
      3 => 'GELENDOST',
      4 => 'GÖNEN',
      5 => 'KEÇİBORLU',
      6 => 'MERKEZ',
      7 => 'SENİRKENT',
      8 => 'SÜTÇÜLER',
      9 => 'ŞARKİKARAAĞAÇ',
      10 => 'ULUBORLU',
      11 => 'YALVAÇ',
      12 => 'YENİŞARBADEMLİ',
    ),
    'İSTANBUL' => 
    array (
      0 => 'ADALAR',
      1 => 'ARNAVUTKÖY',
      2 => 'ATAŞEHİR',
      3 => 'AVCILAR',
      4 => 'BAĞCILAR',
      5 => 'BAHÇELİEVLER',
      6 => 'BAKIRKÖY',
      7 => 'BAŞAKŞEHİR',
      8 => 'BAYRAMPAŞA',
      9 => 'BEŞİKTAŞ',
      10 => 'BEYKOZ',
      11 => 'BEYLİKDÜZÜ',
      12 => 'BEYOĞLU',
      13 => 'BÜYÜKÇEKMECE',
      14 => 'ÇATALCA',
      15 => 'ÇEKMEKÖY',
      16 => 'ESENLER',
      17 => 'ESENYURT',
      18 => 'EYÜPSULTAN',
      19 => 'FATİH',
      20 => 'GAZİOSMANPAŞA',
      21 => 'GÜNGÖREN',
      22 => 'KADIKÖY',
      23 => 'KAĞITHANE',
      24 => 'KARTAL',
      25 => 'KÜÇÜKÇEKMECE',
      26 => 'MALTEPE',
      27 => 'PENDİK',
      28 => 'SANCAKTEPE',
      29 => 'SARIYER',
      30 => 'SİLİVRİ',
      31 => 'SULTANBEYLİ',
      32 => 'SULTANGAZİ',
      33 => 'ŞİLE',
      34 => 'ŞİŞLİ',
      35 => 'TUZLA',
      36 => 'ÜMRANİYE',
      37 => 'ÜSKÜDAR',
      38 => 'ZEYTİNBURNU',
    ),
    'İZMİR' => 
    array (
      0 => 'ALİAĞA',
      1 => 'BALÇOVA',
      2 => 'BAYINDIR',
      3 => 'BAYRAKLI',
      4 => 'BERGAMA',
      5 => 'BEYDAĞ',
      6 => 'BORNOVA',
      7 => 'BUCA',
      8 => 'ÇEŞME',
      9 => 'ÇİĞLİ',
      10 => 'DİKİLİ',
      11 => 'FOÇA',
      12 => 'GAZİEMİR',
      13 => 'GÜZELBAHÇE',
      14 => 'KARABAĞLAR',
      15 => 'KARABURUN',
      16 => 'KARŞIYAKA',
      17 => 'KEMALPAŞA',
      18 => 'KINIK',
      19 => 'KİRAZ',
      20 => 'KONAK',
      21 => 'MENDERES',
      22 => 'MENEMEN',
      23 => 'NARLIDERE',
      24 => 'ÖDEMİŞ',
      25 => 'SEFERİHİSAR',
      26 => 'SELÇUK',
      27 => 'TİRE',
      28 => 'TORBALI',
      29 => 'URLA',
    ),
    'KAHRAMANMARAŞ' => 
    array (
      0 => 'AFŞİN',
      1 => 'ANDIRIN',
      2 => 'ÇAĞLAYANCERİT',
      3 => 'DULKADİROĞLU',
      4 => 'EKİNÖZÜ',
      5 => 'ELBİSTAN',
      6 => 'GÖKSUN',
      7 => 'NURHAK',
      8 => 'ONİKİŞUBAT',
      9 => 'PAZARCIK',
      10 => 'TÜRKOĞLU',
    ),
    'KARABÜK' => 
    array (
      0 => 'EFLANİ',
      1 => 'ESKİPAZAR',
      2 => 'MERKEZ',
      3 => 'OVACIK',
      4 => 'SAFRANBOLU',
      5 => 'YENİCE',
    ),
    'KARAMAN' => 
    array (
      0 => 'AYRANCI',
      1 => 'BAŞYAYLA',
      2 => 'ERMENEK',
      3 => 'KAZIMKARABEKİR',
      4 => 'MERKEZ',
      5 => 'SARIVELİLER',
    ),
    'KARS' => 
    array (
      0 => 'AKYAKA',
      1 => 'ARPAÇAY',
      2 => 'DİGOR',
      3 => 'KAĞIZMAN',
      4 => 'MERKEZ',
      5 => 'SARIKAMIŞ',
      6 => 'SELİM',
      7 => 'SUSUZ',
    ),
    'KASTAMONU' => 
    array (
      0 => 'ABANA',
      1 => 'AĞLI',
      2 => 'ARAÇ',
      3 => 'AZDAVAY',
      4 => 'BOZKURT',
      5 => 'CİDE',
      6 => 'ÇATALZEYTİN',
      7 => 'DADAY',
      8 => 'DEVREKANİ',
      9 => 'DOĞANYURT',
      10 => 'HANÖNÜ',
      11 => 'İHSANGAZİ',
      12 => 'İNEBOLU',
      13 => 'KÜRE',
      14 => 'MERKEZ',
      15 => 'PINARBAŞI',
      16 => 'SEYDİLER',
      17 => 'ŞENPAZAR',
      18 => 'TAŞKÖPRÜ',
      19 => 'TOSYA',
    ),
    'KAYSERİ' => 
    array (
      0 => 'AKKIŞLA',
      1 => 'BÜNYAN',
      2 => 'DEVELİ',
      3 => 'FELAHİYE',
      4 => 'HACILAR',
      5 => 'İNCESU',
      6 => 'KOCASİNAN',
      7 => 'MELİKGAZİ',
      8 => 'ÖZVATAN',
      9 => 'PINARBAŞI',
      10 => 'SARIOĞLAN',
      11 => 'SARIZ',
      12 => 'TALAS',
      13 => 'TOMARZA',
      14 => 'YAHYALI',
      15 => 'YEŞİLHİSAR',
    ),
    'KIRIKKALE' => 
    array (
      0 => 'BAHŞILI',
      1 => 'BALIŞEYH',
      2 => 'ÇELEBİ',
      3 => 'DELİCE',
      4 => 'KARAKEÇİLİ',
      5 => 'KESKİN',
      6 => 'MERKEZ',
      7 => 'SULAKYURT',
      8 => 'YAHŞİHAN',
    ),
    'KIRKLARELİ' => 
    array (
      0 => 'BABAESKİ',
      1 => 'DEMİRKÖY',
      2 => 'KOFÇAZ',
      3 => 'LÜLEBURGAZ',
      4 => 'MERKEZ',
      5 => 'PEHLİVANKÖY',
      6 => 'PINARHİSAR',
      7 => 'VİZE',
    ),
    'KIRŞEHİR' => 
    array (
      0 => 'AKÇAKENT',
      1 => 'AKPINAR',
      2 => 'BOZTEPE',
      3 => 'ÇİÇEKDAĞI',
      4 => 'KAMAN',
      5 => 'MERKEZ',
      6 => 'MUCUR',
    ),
    'KİLİS' => 
    array (
      0 => 'ELBEYLİ',
      1 => 'MERKEZ',
      2 => 'MUSABEYLİ',
      3 => 'POLATELİ',
    ),
    'KOCAELİ' => 
    array (
      0 => 'BAŞİSKELE',
      1 => 'ÇAYIROVA',
      2 => 'DARICA',
      3 => 'DERİNCE',
      4 => 'DİLOVASI',
      5 => 'GEBZE',
      6 => 'GÖLCÜK',
      7 => 'İZMİT',
      8 => 'KANDIRA',
      9 => 'KARAMÜRSEL',
      10 => 'KARTEPE',
      11 => 'KÖRFEZ',
    ),
    'KONYA' => 
    array (
      0 => 'AHIRLI',
      1 => 'AKÖREN',
      2 => 'AKŞEHİR',
      3 => 'ALTINEKİN',
      4 => 'BEYŞEHİR',
      5 => 'BOZKIR',
      6 => 'CİHANBEYLİ',
      7 => 'ÇELTİK',
      8 => 'ÇUMRA',
      9 => 'DERBENT',
      10 => 'DEREBUCAK',
      11 => 'DOĞANHİSAR',
      12 => 'EMİRGAZİ',
      13 => 'EREĞLİ',
      14 => 'GÜNEYSINIR',
      15 => 'HADİM',
      16 => 'HALKAPINAR',
      17 => 'HÜYÜK',
      18 => 'ILGIN',
      19 => 'KADINHANI',
      20 => 'KARAPINAR',
      21 => 'KARATAY',
      22 => 'KULU',
      23 => 'MERAM',
      24 => 'SARAYÖNÜ',
      25 => 'SELÇUKLU',
      26 => 'SEYDİŞEHİR',
      27 => 'TAŞKENT',
      28 => 'TUZLUKÇU',
      29 => 'YALIHÜYÜK',
      30 => 'YUNAK',
    ),
    'KÜTAHYA' => 
    array (
      0 => 'ALTINTAŞ',
      1 => 'ASLANAPA',
      2 => 'ÇAVDARHİSAR',
      3 => 'DOMANİÇ',
      4 => 'DUMLUPINAR',
      5 => 'EMET',
      6 => 'GEDİZ',
      7 => 'HİSARCIK',
      8 => 'MERKEZ',
      9 => 'PAZARLAR',
      10 => 'SİMAV',
      11 => 'ŞAPHANE',
      12 => 'TAVŞANLI',
    ),
    'MALATYA' => 
    array (
      0 => 'AKÇADAĞ',
      1 => 'ARAPGİR',
      2 => 'ARGUVAN',
      3 => 'BATTALGAZİ',
      4 => 'DARENDE',
      5 => 'DOĞANŞEHİR',
      6 => 'DOĞANYOL',
      7 => 'HEKİMHAN',
      8 => 'KALE',
      9 => 'KULUNCAK',
      10 => 'PÜTÜRGE',
      11 => 'YAZIHAN',
      12 => 'YEŞİLYURT',
    ),
    'MANİSA' => 
    array (
      0 => 'AHMETLİ',
      1 => 'AKHİSAR',
      2 => 'ALAŞEHİR',
      3 => 'DEMİRCİ',
      4 => 'GÖLMARMARA',
      5 => 'GÖRDES',
      6 => 'KIRKAĞAÇ',
      7 => 'KÖPRÜBAŞI',
      8 => 'KULA',
      9 => 'SALİHLİ',
      10 => 'SARIGÖL',
      11 => 'SARUHANLI',
      12 => 'SELENDİ',
      13 => 'SOMA',
      14 => 'ŞEHZADELER',
      15 => 'TURGUTLU',
      16 => 'YUNUSEMRE',
    ),
    'MARDİN' => 
    array (
      0 => 'ARTUKLU',
      1 => 'DARGEÇİT',
      2 => 'DERİK',
      3 => 'KIZILTEPE',
      4 => 'MAZIDAĞI',
      5 => 'MİDYAT',
      6 => 'NUSAYBİN',
      7 => 'ÖMERLİ',
      8 => 'SAVUR',
      9 => 'YEŞİLLİ',
    ),
    'MERSİN' => 
    array (
      0 => 'AKDENİZ',
      1 => 'ANAMUR',
      2 => 'AYDINCIK',
      3 => 'BOZYAZI',
      4 => 'ÇAMLIYAYLA',
      5 => 'ERDEMLİ',
      6 => 'GÜLNAR',
      7 => 'MEZİTLİ',
      8 => 'MUT',
      9 => 'SİLİFKE',
      10 => 'TARSUS',
      11 => 'TOROSLAR',
      12 => 'YENİŞEHİR',
    ),
    'MUĞLA' => 
    array (
      0 => 'BODRUM',
      1 => 'DALAMAN',
      2 => 'DATÇA',
      3 => 'FETHİYE',
      4 => 'KAVAKLIDERE',
      5 => 'KÖYCEĞİZ',
      6 => 'MARMARİS',
      7 => 'MENTEŞE',
      8 => 'MİLAS',
      9 => 'ORTACA',
      10 => 'SEYDİKEMER',
      11 => 'ULA',
      12 => 'YATAĞAN',
    ),
    'MUŞ' => 
    array (
      0 => 'BULANIK',
      1 => 'HASKÖY',
      2 => 'KORKUT',
      3 => 'MALAZGİRT',
      4 => 'MERKEZ',
      5 => 'VARTO',
    ),
    'NEVŞEHİR' => 
    array (
      0 => 'ACIGÖL',
      1 => 'AVANOS',
      2 => 'DERİNKUYU',
      3 => 'GÜLŞEHİR',
      4 => 'HACIBEKTAŞ',
      5 => 'KOZAKLI',
      6 => 'MERKEZ',
      7 => 'ÜRGÜP',
    ),
    'NİĞDE' => 
    array (
      0 => 'ALTUNHİSAR',
      1 => 'BOR',
      2 => 'ÇAMARDI',
      3 => 'ÇİFTLİK',
      4 => 'MERKEZ',
      5 => 'ULUKIŞLA',
    ),
    'ORDU' => 
    array (
      0 => 'AKKUŞ',
      1 => 'ALTINORDU',
      2 => 'AYBASTI',
      3 => 'ÇAMAŞ',
      4 => 'ÇATALPINAR',
      5 => 'ÇAYBAŞI',
      6 => 'FATSA',
      7 => 'GÖLKÖY',
      8 => 'GÜLYALI',
      9 => 'GÜRGENTEPE',
      10 => 'İKİZCE',
      11 => 'KABADÜZ',
      12 => 'KABATAŞ',
      13 => 'KORGAN',
      14 => 'KUMRU',
      15 => 'MESUDİYE',
      16 => 'PERŞEMBE',
      17 => 'ULUBEY',
      18 => 'ÜNYE',
    ),
    'OSMANİYE' => 
    array (
      0 => 'BAHÇE',
      1 => 'DÜZİÇİ',
      2 => 'HASANBEYLİ',
      3 => 'KADİRLİ',
      4 => 'MERKEZ',
      5 => 'SUMBAS',
      6 => 'TOPRAKKALE',
    ),
    'RİZE' => 
    array (
      0 => 'ARDEŞEN',
      1 => 'ÇAMLIHEMŞİN',
      2 => 'ÇAYELİ',
      3 => 'DEREPAZARI',
      4 => 'FINDIKLI',
      5 => 'GÜNEYSU',
      6 => 'HEMŞİN',
      7 => 'İKİZDERE',
      8 => 'İYİDERE',
      9 => 'KALKANDERE',
      10 => 'MERKEZ',
      11 => 'PAZAR',
    ),
    'SAKARYA' => 
    array (
      0 => 'ADAPAZARI',
      1 => 'AKYAZI',
      2 => 'ARİFİYE',
      3 => 'ERENLER',
      4 => 'FERİZLİ',
      5 => 'GEYVE',
      6 => 'HENDEK',
      7 => 'KARAPÜRÇEK',
      8 => 'KARASU',
      9 => 'KAYNARCA',
      10 => 'KOCAALİ',
      11 => 'PAMUKOVA',
      12 => 'SAPANCA',
      13 => 'SERDİVAN',
      14 => 'SÖĞÜTLÜ',
      15 => 'TARAKLI',
    ),
    'SAMSUN' => 
    array (
      0 => '19 MAYIS',
      1 => 'ALAÇAM',
      2 => 'ASARCIK',
      3 => 'ATAKUM',
      4 => 'AYVACIK',
      5 => 'BAFRA',
      6 => 'CANİK',
      7 => 'ÇARŞAMBA',
      8 => 'HAVZA',
      9 => 'İLKADIM',
      10 => 'KAVAK',
      11 => 'LADİK',
      12 => 'SALIPAZARI',
      13 => 'TEKKEKÖY',
      14 => 'TERME',
      15 => 'VEZİRKÖPRÜ',
      16 => 'YAKAKENT',
    ),
    'SİİRT' => 
    array (
      0 => 'BAYKAN',
      1 => 'ERUH',
      2 => 'KURTALAN',
      3 => 'MERKEZ',
      4 => 'PERVARİ',
      5 => 'ŞİRVAN',
      6 => 'TİLLO',
    ),
    'SİNOP' => 
    array (
      0 => 'AYANCIK',
      1 => 'BOYABAT',
      2 => 'DİKMEN',
      3 => 'DURAĞAN',
      4 => 'ERFELEK',
      5 => 'GERZE',
      6 => 'MERKEZ',
      7 => 'SARAYDÜZÜ',
      8 => 'TÜRKELİ',
    ),
    'SİVAS' => 
    array (
      0 => 'AKINCILAR',
      1 => 'ALTINYAYLA',
      2 => 'DİVRİĞİ',
      3 => 'DOĞANŞAR',
      4 => 'GEMEREK',
      5 => 'GÖLOVA',
      6 => 'GÜRÜN',
      7 => 'HAFİK',
      8 => 'İMRANLI',
      9 => 'KANGAL',
      10 => 'KOYULHİSAR',
      11 => 'MERKEZ',
      12 => 'SUŞEHRİ',
      13 => 'ŞARKIŞLA',
      14 => 'ULAŞ',
      15 => 'YILDIZELİ',
      16 => 'ZARA',
    ),
    'ŞANLIURFA' => 
    array (
      0 => 'AKÇAKALE',
      1 => 'BİRECİK',
      2 => 'BOZOVA',
      3 => 'CEYLANPINAR',
      4 => 'EYYÜBİYE',
      5 => 'HALFETİ',
      6 => 'HALİLİYE',
      7 => 'HARRAN',
      8 => 'HİLVAN',
      9 => 'KARAKÖPRÜ',
      10 => 'SİVEREK',
      11 => 'SURUÇ',
      12 => 'VİRANŞEHİR',
    ),
    'ŞIRNAK' => 
    array (
      0 => 'BEYTÜŞŞEBAP',
      1 => 'CİZRE',
      2 => 'GÜÇLÜKONAK',
      3 => 'İDİL',
      4 => 'MERKEZ',
      5 => 'SİLOPİ',
      6 => 'ULUDERE',
    ),
    'TEKİRDAĞ' => 
    array (
      0 => 'ÇERKEZKÖY',
      1 => 'ÇORLU',
      2 => 'ERGENE',
      3 => 'HAYRABOLU',
      4 => 'KAPAKLI',
      5 => 'MALKARA',
      6 => 'MARMARAEREĞLİSİ',
      7 => 'MURATLI',
      8 => 'SARAY',
      9 => 'SÜLEYMANPAŞA',
      10 => 'ŞARKÖY',
    ),
    'TOKAT' => 
    array (
      0 => 'ALMUS',
      1 => 'ARTOVA',
      2 => 'BAŞÇİFTLİK',
      3 => 'ERBAA',
      4 => 'MERKEZ',
      5 => 'NİKSAR',
      6 => 'PAZAR',
      7 => 'REŞADİYE',
      8 => 'SULUSARAY',
      9 => 'TURHAL',
      10 => 'YEŞİLYURT',
      11 => 'ZİLE',
    ),
    'TRABZON' => 
    array (
      0 => 'AKÇAABAT',
      1 => 'ARAKLI',
      2 => 'ARSİN',
      3 => 'BEŞİKDÜZÜ',
      4 => 'ÇARŞIBAŞI',
      5 => 'ÇAYKARA',
      6 => 'DERNEKPAZARI',
      7 => 'DÜZKÖY',
      8 => 'HAYRAT',
      9 => 'KÖPRÜBAŞI',
      10 => 'MAÇKA',
      11 => 'OF',
      12 => 'ORTAHİSAR',
      13 => 'SÜRMENE',
      14 => 'ŞALPAZARI',
      15 => 'TONYA',
      16 => 'VAKFIKEBİR',
      17 => 'YOMRA',
    ),
    'TUNCELİ' => 
    array (
      0 => 'ÇEMİŞGEZEK',
      1 => 'HOZAT',
      2 => 'MAZGİRT',
      3 => 'MERKEZ',
      4 => 'NAZIMİYE',
      5 => 'OVACIK',
      6 => 'PERTEK',
      7 => 'PÜLÜMÜR',
    ),
    'UŞAK' => 
    array (
      0 => 'BANAZ',
      1 => 'EŞME',
      2 => 'KARAHALLI',
      3 => 'MERKEZ',
      4 => 'SİVASLI',
      5 => 'ULUBEY',
    ),
    'VAN' => 
    array (
      0 => 'BAHÇESARAY',
      1 => 'BAŞKALE',
      2 => 'ÇALDIRAN',
      3 => 'ÇATAK',
      4 => 'EDREMİT',
      5 => 'ERCİŞ',
      6 => 'GEVAŞ',
      7 => 'GÜRPINAR',
      8 => 'İPEKYOLU',
      9 => 'MURADİYE',
      10 => 'ÖZALP',
      11 => 'SARAY',
      12 => 'TUŞBA',
    ),
    'YALOVA' => 
    array (
      0 => 'ALTINOVA',
      1 => 'ARMUTLU',
      2 => 'ÇINARCIK',
      3 => 'ÇİFTLİKKÖY',
      4 => 'MERKEZ',
      5 => 'TERMAL',
    ),
    'YOZGAT' => 
    array (
      0 => 'AKDAĞMADENİ',
      1 => 'AYDINCIK',
      2 => 'BOĞAZLIYAN',
      3 => 'ÇANDIR',
      4 => 'ÇAYIRALAN',
      5 => 'ÇEKEREK',
      6 => 'KADIŞEHRİ',
      7 => 'MERKEZ',
      8 => 'SARAYKENT',
      9 => 'SARIKAYA',
      10 => 'SORGUN',
      11 => 'ŞEFAATLİ',
      12 => 'YENİFAKILI',
      13 => 'YERKÖY',
    ),
    'ZONGULDAK' => 
    array (
      0 => 'ALAPLI',
      1 => 'ÇAYCUMA',
      2 => 'DEVREK',
      3 => 'EREĞLİ',
      4 => 'GÖKÇEBEY',
      5 => 'KİLİMLİ',
      6 => 'KOZLU',
      7 => 'MERKEZ',
    ),
  ),
);
