<?php

namespace App\Support;

final class CategorySeoFacts
{
    /**
     * @return array<string, array{
     *     hook: string,
     *     uses: list<string>,
     *     criteria: list<string>,
     *     mistake: string,
     *     related: list<array{href: string, label: string}>,
     *     brands_note?: string,
     *     table?: list<array{0: string, 1: string, 2: string}>,
     *     blog?: array{href: string, label: string},
     *     closing?: string,
     *     guide_closing?: string
     * }>
     */
    public static function all(): array
    {
        $heaterClosing = <<<'HTML'
<p><strong>Ardonat</strong> ve diğer orijinal elektrikli ısıtıcıları Koşar Ticaret stokundan teknik özellikleriyle sunuyoruz. Model seçerken ısıtılacak alanın açık/yarı açık/kapalı oluşunu, montaj tipini (duvar, dikey tower, panel), güç kademesini ve kumanda ihtiyacını paylaşın; <a href="/marka/ardonat">Ardonat ısıtıcı modelleri</a> ile <a href="/iletisim">teknik destek</a> üzerinden doğru seriyi netleştiririz. 1.000 TL üzeri siparişlerde ücretsiz kargo seçenekleri geçerlidir.</p>
HTML;
        $heaterGuideClosing = <<<'HTML'
<p>Alternatif ürün tiplerini görmek için ilgili kategori sayfalarına bakabilir; kararsız kaldığınız noktada alan ölçüsü, montaj yüksekliği ve kullanım süresini <a href="/iletisim">teknik destek</a> üzerinden paylaşabilirsiniz. Marka ve seri karşılaştırması için <a href="/marka/ardonat">Ardonat ürünleri</a> sayfasını inceleyin.</p>
HTML;

        return [
            'elektrik-ve-aydinlatma' => [
                'hook' => 'Elektrik ve aydınlatma ürünleri, bir mekânın güvenli enerji dağıtımı ile görsel konforunu birlikte kurar.',
                'uses' => ['Konut içi genel ve görev aydınlatması', 'Bahçe, cephe ve ıslak hacim uygulamaları', 'Atölye ve depo çalışma alanları', 'Anahtar, priz ve yardımcı elektrik ihtiyaçları'],
                'criteria' => ['Armatürün lümen değeri ve ışık rengi', 'Montaj yerinin IP koruma sınıfı', 'Besleme gerilimi ve duy uyumu', 'Alan ölçüsü ile kullanım süresi'],
                'mistake' => 'Yalnız watt değerine bakıp lümen, renk sıcaklığı ve koruma sınıfını göz ardı etmek karanlık, yorucu veya kısa ömürlü bir kurulum oluşturabilir.',
                'related' => [['href' => '/kategoriler/vantilatorler', 'label' => 'Vantilatörler'], ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar', 'label' => 'Elektrikli ısıtıcılar']],
            ],
            'hidrofor-sistemleri' => [
                'hook' => 'Hidrofor sistemleri, şebeke veya depo suyunu kullanım noktalarında kararlı basınca dönüştüren otomatik paket çözümlerdir.',
                'uses' => ['Müstakil ev ve yazlıklarda basınç artırma', 'Apartmanlarda eşzamanlı su kullanımı', 'İşyeri ve küçük tesis beslemesi', 'Depodan tesisata otomatik su basma'],
                'criteria' => ['Kat ve daire sayısına göre eşzamanlı debi', 'En üst kullanım noktasının kotu', 'Tank hacmi ve devreye girme sıklığı', 'Tek pompalı veya yedekli çalışma ihtiyacı'],
                'mistake' => 'Sadece motor gücünü büyütmek doğru çözüm değildir; gereğinden büyük hidrofor sık dur-kalk, gürültü ve tesisatta aşırı basınç yaratabilir.',
                'related' => [['href' => '/kategoriler/hidrofor-sistemleri/ev-tipi-hidroforlar', 'label' => 'Ev tipi hidroforlar'], ['href' => '/kategoriler/hidrofor-sistemleri/hidrofor-grubu', 'label' => 'Hidrofor grupları'], ['href' => '/kategoriler/su-pompalari', 'label' => 'Su pompaları']],
                'brands_note' => 'Pedrollo, Sumak ve Winpo seçenekleri; proje debisi, kontrol biçimi ve servis erişimi üzerinden karşılaştırılabilir.',
                'table' => [['Ev tipi', 'Tek konut ve yazlık', 'Kompakt tanklı çözüm'], ['Grup hidrofor', 'Apartman ve tesis', 'Yedekli veya çok pompalı'], ['Hidromatlı', 'Değişken küçük tüketim', 'Elektronik otomasyon']],
                'blog' => ['href' => '/blog/hidrofor-nedir-ne-ise-yarar-nasil-calisir', 'label' => 'Hidroforun çalışma prensibi'],
            ],
            'su-pompalari' => [
                'hook' => 'Su pompaları; kaynaktaki suyu gerekli debi ve basınçla sulama, bina veya proses hattına taşır.',
                'uses' => ['Bahçe ve tarla sulama hatları', 'Kuyu, sarnıç ve depodan su alma', 'Bina tesisatında basınçlandırma', 'Drenaj ve atık su tahliyesi', 'Isıtma devrelerinde sirkülasyon'],
                'criteria' => ['İstenen debi ve toplam basma yüksekliği', 'Temiz, kirli veya kimyasal sıvı yapısı', 'Yüzey ya da su altında kurulum', 'Monofaze veya trifaze elektrik beslemesi', 'Boru çapı ve hat kayıpları'],
                'mistake' => 'Pompayı yalnız beygir gücüne göre seçmek, çalışma noktasında yetersiz debiye veya gereksiz enerji tüketimine neden olur.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar', 'label' => 'Dalgıç pompalar'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar', 'label' => 'Santrifüj pompalar'], ['href' => '/kategoriler/hidrofor-sistemleri', 'label' => 'Hidrofor sistemleri']],
                'brands_note' => 'Pedrollo, Sumak, Winpo ve Kaysu ürünlerini aynı çalışma noktasındaki eğri değerleriyle kıyaslamak daha sağlıklı sonuç verir.',
                'table' => [['Dalgıç', 'Kuyu ve tahliye', 'Sıvı içinde çalışır'], ['Santrifüj', 'Sulama ve transfer', 'Yüzeyde kolay bakım'], ['Kademeli', 'Yüksek basınç', 'Birden çok çark kademesi']],
                'blog' => ['href' => '/blog/su-pompasi-cesitleri-nasil-secilir', 'label' => 'Su pompası seçim rehberi'],
            ],
            'vantilatorler' => [
                'hook' => 'Vantilatörler, yaşam ve çalışma alanlarında hava hareketi oluşturarak ısı hissini ve havalandırma koşullarını iyileştirir.',
                'uses' => ['Ev ve ofiste serinletme', 'Atölyede çalışan konforu', 'Depoda hava dolaşımı', 'Üretim alanında lokal hava yönlendirme'],
                'criteria' => ['Alan hacmine uygun hava debisi', 'Ses seviyesi ve kullanım mesafesi', 'Kanat çapı ile hız kademeleri', 'Sabit, salınımlı veya taşınabilir kurulum'],
                'mistake' => 'Küçük bir ev fanını yüksek sıcaklıklı ve tozlu sanayi ortamında sürekli çalıştırmak motor ömrünü kısaltır ve beklenen hava değişimini sağlamaz.',
                'related' => [['href' => '/kategoriler/vantilatorler/ev-tipi-vantilator', 'label' => 'Ev tipi vantilatörler'], ['href' => '/kategoriler/vantilatorler/sanayi-tipi-vantilator', 'label' => 'Sanayi tipi vantilatörler'], ['href' => '/kategoriler/elektrik-ve-aydinlatma', 'label' => 'Elektrik ve aydınlatma']],
                'table' => [['Ev tipi', 'Oda ve ofis', 'Düşük ses önceliği'], ['Sanayi tipi', 'Depo ve atölye', 'Yüksek debi ve dayanım'], ['Duvar tipi', 'Dar zemin alanı', 'Sabit güvenli montaj']],
            ],
            'su-pompalari/dalgic-pompalar' => [
                'hook' => 'Dalgıç pompalar, motor ve hidrolik gövde sıvı içinde çalıştığı için emiş hattı kurmadan kuyudan veya çukurdan su alır.',
                'uses' => ['Sondaj ve keson kuyudan su çıkarma', 'Bodrum ile otopark drenajı', 'Foseptik ve kirli su tahliyesi', 'Sarnıçtan sulama hattı besleme'],
                'criteria' => ['Kuyu çapı veya çukur ölçüsü', 'Partikül geçiş çapı', 'Dinamik su seviyesi ve basma kotu', 'Şamandıra ile kuru çalışma koruması'],
                'mistake' => 'Temiz su için tasarlanmış dar geçişli bir modeli lifli atıkta kullanmak çarkın sık sık tıkanmasına ve motorun zorlanmasına yol açar.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/derin-kuyu-dalgic-pompa', 'label' => 'Derin kuyu pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/drenaj-dalgic-pompa', 'label' => 'Drenaj pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/foseptik-dalgic-pompa', 'label' => 'Foseptik pompaları']],
                'blog' => ['href' => '/blog/dalgic-pompa-nedir-nasil-secilir', 'label' => 'Dalgıç pompa seçim adımları'],
            ],
            'su-pompalari/jet-pompalar-derinden-emisli' => [
                'hook' => 'Derinden emişli jet pompalar, ejektör etkisiyle yüzey pompalarının standart emiş sınırını belirli kuyu koşullarında genişletir.',
                'uses' => ['Sığ ve orta derinlikte keson kuyular', 'Bahçe sulama suyu temini', 'Kırsal konut depo beslemesi', 'Hidrofor paketi oluşturma'],
                'criteria' => ['Gerçek dinamik emiş seviyesi', 'Emiş borusunun çapı ve sızdırmazlığı', 'Ejektör ile pompa model uyumu', 'İstenen çıkış debisi ve basıncı'],
                'mistake' => 'Kuyu derinliğini su seviyesine eşit sanmak ve emiş hattındaki hava kaçağını hesaba katmamak pompanın su alamamasına neden olabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/derin-kuyu-dalgic-pompa', 'label' => 'Derin kuyu dalgıç pompalar'], ['href' => '/kategoriler/hidrofor-sistemleri/ev-tipi-hidroforlar', 'label' => 'Ev tipi hidroforlar'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar', 'label' => 'Santrifüj pompalar']],
            ],
            'su-pompalari/kademeli-pompalar' => [
                'hook' => 'Kademeli pompalar, ardışık çarkların basıncını birleştirerek orta debide yüksek basma yüksekliği sağlar.',
                'uses' => ['Çok katlı bina basınçlandırması', 'Ters osmoz ve proses beslemesi', 'Uzun mesafeli sulama hatları', 'Kazan ve tank dolum sistemleri'],
                'criteria' => ['Çalışma noktasındaki kademe sayısı', 'Dikey veya yatay montaj alanı', 'Akışkan sıcaklığı ve gövde malzemesi', 'Mekanik salmastra ile motor verimi'],
                'mistake' => 'En fazla basma değerini sürekli çalışma noktası kabul etmek, debi açıldığında basıncın beklenenden hızlı düşmesine yol açar.',
                'related' => [['href' => '/kategoriler/su-pompalari/kademeli-pompalar/dikey-kademeli-pompalar', 'label' => 'Dikey kademeli pompalar'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar/yatay-kademeli-pompalar', 'label' => 'Yatay kademeli pompalar'], ['href' => '/kategoriler/hidrofor-sistemleri/hidrofor-grubu', 'label' => 'Hidrofor grupları']],
            ],
            'su-pompalari/preferikal-pompalar-surtme-fanli' => [
                'hook' => 'Periferik sürtme fanlı pompalar, kompakt gövdede düşük debiyi görece yüksek basınca çıkaran pratik yüzey pompalarıdır.',
                'uses' => ['Küçük bahçe sulama', 'Tek noktaya temiz su basma', 'Makine yardımcı su devresi', 'Kompakt ev tipi hidrofor'],
                'criteria' => ['Temiz ve tortusuz su koşulu', 'Düşük debi ihtiyacı', 'Kısa ve sızdırmaz emiş hattı', 'Çalışma süresi ile motor soğutması'],
                'mistake' => 'Bu pompa tipini yüksek debi isteyen geniş sulama hattına seçmek, basınç varmış gibi görünürken uç noktalarda yetersiz suya neden olur.',
                'related' => [['href' => '/kategoriler/su-pompalari/jet-pompalar-derinden-emisli', 'label' => 'Jet pompalar'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/tek-fanli-santrifuj-pompa', 'label' => 'Tek fanlı santrifüj pompalar'], ['href' => '/kategoriler/hidrofor-sistemleri/ev-tipi-hidroforlar', 'label' => 'Ev tipi hidroforlar']],
            ],
            'su-pompalari/santrifuj-pompalar' => [
                'hook' => 'Santrifüj pompalar, dönen çarkın enerjisini akışa aktararak sulama ve tesisatlarda sürekli su transferi sağlar.',
                'uses' => ['Tarla ve bahçe sulama', 'Depolar arası su transferi', 'Bina mekanik tesisatı', 'Hafif endüstriyel prosesler'],
                'criteria' => ['Pompa eğrisinde debi-basma kesişimi', 'Emiş yüksekliği ve NPSH koşulu', 'Tek ya da çift fan ihtiyacı', 'Döküm veya paslanmaz gövde seçimi'],
                'mistake' => 'Pompayı susuz çalıştırmak veya ilk devreye almada gövdeyi suyla doldurmamak mekanik salmastrayı kısa sürede bozabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/tek-fanli-santrifuj-pompa', 'label' => 'Tek fanlı pompalar'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/cift-fanli-santrifuj-pompa', 'label' => 'Çift fanlı pompalar'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/paslanmaz-pompalar-kimyasal', 'label' => 'Paslanmaz pompalar']],
            ],
            'su-pompalari/sirkulasyon-pompalari' => [
                'hook' => 'Sirkülasyon pompaları, kapalı ısıtma ve sıcak su devrelerinde akışkanı tüketmeden çevrim halinde dolaştırır.',
                'uses' => ['Radyatörlü kalorifer devreleri', 'Yerden ısıtma kollektörleri', 'Kullanım sıcak suyu devridaimi', 'Kazan ve eşanjör çevrimleri'],
                'criteria' => ['Tesisat debisi ve sürtünme kaybı', 'Akışkanın çalışma sıcaklığı', 'Bağlantı tipi ile montaj boyu', 'Sabit veya değişken devir kontrolü'],
                'mistake' => 'Açık sistem su transferi için sirkülasyon pompası seçmek veya gereğinden büyük model kullanmak gürültü ve balans sorunları doğurur.',
                'related' => [['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/flansli-sirkulasyon-pompalari', 'label' => 'Flanşlı sirkülasyon pompaları'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/rekorlu-disli-sirkulasyon-pompalari', 'label' => 'Rekorlu sirkülasyon pompaları'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/sicak-su-pompalari', 'label' => 'Sıcak su pompaları']],
                'blog' => ['href' => '/blog/sirkulasyon-pompasi-nedir-nasil-secilir', 'label' => 'Sirkülasyon pompası rehberi'],
            ],
            'su-pompalari/su-pompasi' => [
                'hook' => 'Genel amaçlı su pompaları, temiz suyun depodan bahçeye veya bir tesisat bölümünden diğerine aktarılmasında esnek çözümler sunar.',
                'uses' => ['Varil ve depo boşaltma', 'Hobi bahçesi sulama', 'Küçük yapı su beslemesi', 'Geçici su transferi'],
                'criteria' => ['Kaynak ile çıkış arasındaki kot farkı', 'Saatlik su ihtiyacı', 'Taşınabilirlik ve bağlantı çapı', 'Kesintili ya da sürekli çalışma biçimi'],
                'mistake' => 'Ürün etiketindeki maksimum debi ile maksimum basmayı aynı anda elde edilecek değerler sanmak gerçek kullanımda hayal kırıklığı yaratır.',
                'related' => [['href' => '/kategoriler/su-pompalari/santrifuj-pompalar', 'label' => 'Santrifüj pompalar'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar', 'label' => 'Dalgıç pompalar'], ['href' => '/pompa-secici', 'label' => 'Pompa Seçici']],
            ],
            'su-pompalari/ozel-amacli-pompalar' => [
                'hook' => 'Özel amaçlı pompalar, standart temiz su transferinden farklı akışkan, güvenlik veya sistem koşulları için geliştirilir.',
                'uses' => ['Yangın tesisatı basınçlandırması', 'Havuz ve jakuzi filtrasyonu', 'Foseptik tahliye paketleri', 'Yağmur suyu ve saha drenajı', 'Elektriksiz alanlarda dizel transfer'],
                'criteria' => ['Uygulamaya özel standart ve görev tanımı', 'Katı madde veya kimyasal uyumu', 'Yedeklilik ve kontrol panosu ihtiyacı', 'Bakım erişimi ile çalışma süresi'],
                'mistake' => 'Genel amaçlı bir pompayı özel akışkana ya da can güvenliği sistemine uyarlamaya çalışmak malzeme ve performans açısından risklidir.',
                'related' => [['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/yangin-pompalari', 'label' => 'Yangın pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/on-filtreli-havuz-pompasi', 'label' => 'Havuz pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/yagmur-suyu-tahliye-pompasi', 'label' => 'Yağmur suyu pompaları']],
            ],
            'vantilatorler/ev-tipi-vantilator' => [
                'hook' => 'Ev tipi vantilatörler, odada hedefli hava akışı sağlayarak klima kullanılmayan veya desteklenen dönemlerde konforu artırır.',
                'uses' => ['Yatak odasında gece serinliği', 'Salon ve çalışma odası dolaşımı', 'Balkon ile kapalı teras kullanımı', 'Masa başında kişisel hava akışı'],
                'criteria' => ['Düşük kademedeki ses seviyesi', 'Salınım açısı ve yükseklik ayarı', 'Kanat çapına uygun oda büyüklüğü', 'Zamanlayıcı ve uzaktan kumanda ihtiyacı'],
                'mistake' => 'Sadece en yüksek hızdaki debiye odaklanmak, gece kullanımında gürültülü ve gereğinden sert bir hava akışı seçilmesine neden olabilir.',
                'related' => [['href' => '/kategoriler/vantilatorler', 'label' => 'Tüm vantilatörler'], ['href' => '/kategoriler/vantilatorler/sanayi-tipi-vantilator', 'label' => 'Sanayi tipi vantilatörler'], ['href' => '/kategoriler/elektrik-ve-aydinlatma', 'label' => 'Elektrik ve aydınlatma']],
            ],
            'vantilatorler/sanayi-tipi-vantilator' => [
                'hook' => 'Sanayi tipi vantilatörler, geniş hacimlerde yüksek hava debisini dayanıklı motor ve gövdeyle uzun süre üretmek üzere tasarlanır.',
                'uses' => ['Fabrika üretim alanı serinletme', 'Depo içinde hava homojenleştirme', 'Atölyede lokal çalışma istasyonu', 'Sevkiyat ve yükleme alanı havalandırma'],
                'criteria' => ['m³/saat cinsinden gerekli hava debisi', 'Toz, nem ve sıcaklık ortamı', 'Duvar, ayaklı veya mobil yerleşim', 'Motor koruma sınıfı ve çalışma rejimi'],
                'mistake' => 'Kanat çapını tek başına kapasite göstergesi saymak, alanın hava değişim ihtiyacı karşılanmadığında ölü bölgeler bırakabilir.',
                'related' => [['href' => '/kategoriler/vantilatorler/ev-tipi-vantilator', 'label' => 'Ev tipi vantilatörler'], ['href' => '/kategoriler/vantilatorler', 'label' => 'Vantilatörler'], ['href' => '/kategoriler/elektrik-ve-aydinlatma', 'label' => 'Elektrik ürünleri']],
            ],
            'hidrofor-sistemleri/ev-tipi-hidroforlar' => [
                'hook' => 'Ev tipi hidroforlar, tek konutun musluk ve cihazlarında depo suyunu otomatik, dengeli basınca getirir.',
                'uses' => ['Müstakil ev depo beslemesi', 'Yazlık ve bağ evi tesisatı', 'Tek dairede düşük şebeke basıncı', 'Bahçe ile evin ortak su kullanımı'],
                'criteria' => ['Aynı anda açılabilecek kullanım noktaları', 'En üst musluğa olan yükseklik', '24 veya 50 litre tank seçimi', 'Pompa sesinin kurulum alanına etkisi'],
                'mistake' => 'Küçük tankla yüksek ve sık tüketimi beslemek pompanın dakikada birçok kez devreye girmesine, tank ve motor ömrünün azalmasına yol açar.',
                'related' => [['href' => '/kategoriler/hidrofor-sistemleri/hidroforlar', 'label' => 'Hidroforlar'], ['href' => '/kategoriler/hidrofor-sistemleri/hidromat', 'label' => 'Hidromatlar'], ['href' => '/kategoriler/su-pompalari/jet-pompalar-derinden-emisli', 'label' => 'Jet pompalar']],
            ],
            'hidrofor-sistemleri/hidrofor-grubu' => [
                'hook' => 'Hidrofor grupları, birden fazla pompayı sıralı veya değişken hızlı çalıştırarak yüksek tüketimde süreklilik sağlar.',
                'uses' => ['Çok daireli apartmanlar', 'Otel ve yurt yapıları', 'Üretim ve idari tesisler', 'Yedek pompa gereken kritik hatlar'],
                'criteria' => ['Pik saat eşzamanlı debisi', 'Asil-yedek pompa senaryosu', 'Frekans konvertörü ve pano mantığı', 'Kollektör çapı ile tank hacmi'],
                'mistake' => 'Toplam ihtiyacı tek pompaya yüklemek arıza anında suyu tamamen keser; grup seçiminin yedeklilik senaryosu baştan belirlenmelidir.',
                'related' => [['href' => '/kategoriler/hidrofor-sistemleri', 'label' => 'Hidrofor sistemleri'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar/dikey-kademeli-pompalar', 'label' => 'Dikey kademeli pompalar'], ['href' => '/kategoriler/hidrofor-sistemleri/hidromat', 'label' => 'Hidromatlar']],
            ],
            'hidrofor-sistemleri/hidroforlar' => [
                'hook' => 'Hazır hidroforlar, pompa, basınç tankı ve kontrol elemanlarını montaja uygun tek bir basınçlandırma paketinde birleştirir.',
                'uses' => ['Evde musluk basıncını dengeleme', 'Depodan otomatik su alma', 'Küçük işletme tesisatı', 'Bahçe sulama hattını basınçlandırma'],
                'criteria' => ['Pompa eğrisindeki görev noktası', 'Tank ön gaz basıncı ve hacmi', 'Basınç şalteri ayar aralığı', 'Emiş koşulu ve çekvalf düzeni'],
                'mistake' => 'Hidroforun pompa kısmını depodan daha yükseğe ve uzun dar emiş hattıyla kurmak kavitasyon ile düzensiz devreye girmeye neden olabilir.',
                'related' => [['href' => '/kategoriler/hidrofor-sistemleri/ev-tipi-hidroforlar', 'label' => 'Ev tipi hidroforlar'], ['href' => '/kategoriler/hidrofor-sistemleri/pedrollo-hidrofor', 'label' => 'Pedrollo hidroforlar'], ['href' => '/kategoriler/hidrofor-sistemleri/sumak-hidrofor', 'label' => 'Sumak hidroforlar']],
            ],
            'hidrofor-sistemleri/hidromat' => [
                'hook' => 'Hidromat, pompayı akış ve basınç bilgisine göre yöneten, klasik basınç şalteri-tank düzenine elektronik alternatif sunan kontrol cihazıdır.',
                'uses' => ['Bahçe sulama pompasını otomatikleştirme', 'Kompakt konut su beslemesi', 'Depodan musluk açılınca çalışma', 'Kuru çalışma riskini azaltma'],
                'criteria' => ['Pompa gücü ve akım uyumu', 'Başlatma basıncı', 'Minimum akış algılama değeri', 'Dikey montaj ve su sızdırmazlığı'],
                'mistake' => 'Hidromatı her tesisatta basınç tankının birebir karşılığı saymak, küçük kaçaklarda sık devreye girme ve basınç dalgalanması oluşturabilir.',
                'related' => [['href' => '/kategoriler/hidrofor-sistemleri/hidroforlar', 'label' => 'Hidroforlar'], ['href' => '/kategoriler/hidrofor-sistemleri/ev-tipi-hidroforlar', 'label' => 'Ev tipi hidroforlar'], ['href' => '/kategoriler/su-pompalari/su-pompasi', 'label' => 'Su pompaları']],
            ],
            'hidrofor-sistemleri/pedrollo-hidrofor' => [
                'hook' => 'Pedrollo hidroforlar, markanın jet, santrifüj veya kademeli pompalarını otomatik basınç ekipmanlarıyla paketler.',
                'uses' => ['Villa ve müstakil ev basınçlandırması', 'Apartman ortak su sistemi', 'İşyeri ve atölye beslemesi', 'Depo suyuyla bahçe kullanımı'],
                'criteria' => ['Pedrollo pompa serisinin eğri noktası', 'Tank hacmi ve membran tipi', 'Tek veya üç fazlı besleme', 'Orijinal kontrol ekipmanı uyumu'],
                'mistake' => 'Sadece marka ve beygir gücü eşleşmesine güvenmek, farklı kat yüksekliği ve debi ihtiyacında aynı modelin yanlış kullanılmasına neden olur.',
                'related' => [['href' => '/marka/pedrollo', 'label' => 'Pedrollo markası'], ['href' => '/kategoriler/hidrofor-sistemleri/hidroforlar', 'label' => 'Tüm hidroforlar'], ['href' => '/kategoriler/hidrofor-sistemleri/sumak-hidrofor', 'label' => 'Sumak hidroforlar']],
                'brands_note' => 'Pedrollo serilerinde orijinal ürün kodunu, pompa eğrisini ve paket içindeki tank-kontrol bileşenlerini birlikte doğrulayın.',
            ],
            'hidrofor-sistemleri/sumak-hidrofor' => [
                'hook' => 'Sumak hidroforlar, yerli üretim pompa ve yaygın parça erişimini konut ile küçük bina basınçlandırma paketlerinde bir araya getirir.',
                'uses' => ['Tek ve çift katlı konutlar', 'Küçük apartman sistemleri', 'Atölye kullanım suyu', 'Yazlık depo çıkışı'],
                'criteria' => ['SKS veya SKT seri kapasitesi', 'Tank litre değeri', 'Servis alanına uygun yerleşim', 'Günlük devreye girme sıklığı'],
                'mistake' => 'Tank hacmini yalnız yer kaplamasına göre küçültmek, motorun çok sık çalışmasına ve enerji tüketiminin artmasına yol açabilir.',
                'related' => [['href' => '/marka/sumak', 'label' => 'Sumak markası'], ['href' => '/kategoriler/hidrofor-sistemleri/hidroforlar', 'label' => 'Hidroforlar'], ['href' => '/kategoriler/hidrofor-sistemleri/pedrollo-hidrofor', 'label' => 'Pedrollo hidroforlar']],
                'brands_note' => 'Sumak paketlerinde seri kodu, tank kapasitesi ve faz seçeneği aynı isim altında değişebildiği için teknik etiketi kontrol etmek önemlidir.',
            ],
            'hidrofor-sistemleri/sicak-su-hidroforu' => [
                'hook' => 'Sıcak su hidroforları, sıcak akışkanla temas eden gövde, conta ve tank bileşenleri uygun seçilmiş basınçlandırma sistemleridir.',
                'uses' => ['Boyler çıkışında basınç desteği', 'Güneş enerjisi sıcak su hattı', 'Otel ve hamam kullanım suyu', 'Proses sıcak su beslemesi'],
                'criteria' => ['Sürekli ve azami akışkan sıcaklığı', 'Conta ile membran malzemesi', 'Sıcaklıkta gerekli debi-basınç', 'Genleşme ve emniyet ekipmanları'],
                'mistake' => 'Soğuk su için üretilmiş standart tank ve contaları sıcak hatta kullanmak erken membran bozulması ve sızıntı riski yaratır.',
                'related' => [['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/sicak-su-pompalari', 'label' => 'Sıcak su sirkülasyon pompaları'], ['href' => '/kategoriler/hidrofor-sistemleri/hidroforlar', 'label' => 'Standart hidroforlar'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari', 'label' => 'Sirkülasyon pompaları']],
            ],
            'su-pompalari/dalgic-pompalar/bicakli-dalgic-pompa' => [
                'hook' => 'Bıçaklı dalgıç pompalar, lifli ve parçalanabilir atıkları girişte keserek dar basma hatlarında tıkanma riskini azaltır.',
                'uses' => ['Konut tipi foseptik çukurları', 'Tuvalet atığı tahliyesi', 'Küçük işletme atık suyu', 'Lifli organik sıvı transferi'],
                'criteria' => ['Bıçak mekanizmasının atığa uygunluğu', 'Katı madde oranı', 'Basma borusu çapı ve uzunluğu', 'Motor termik koruması'],
                'mistake' => 'Taş, metal veya yoğun kum bulunan çukurda bıçaklı model kullanmak kesici mekanizmaya zarar verebilir; bu ortamlar farklı hidrolik ister.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/foseptik-dalgic-pompa', 'label' => 'Foseptik pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/kirli-su-dalgic-pompa', 'label' => 'Kirli su pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/foseptik-tahliye-cihazi', 'label' => 'Foseptik tahliye cihazları']],
            ],
            'su-pompalari/dalgic-pompalar/dalgic-pompa' => [
                'hook' => 'Genel dalgıç pompa seçenekleri, su kaynağının içinde çalışarak kompakt kurulum ve emişsiz ilk hareket avantajı sağlar.',
                'uses' => ['Sarnıçtan su transferi', 'Küçük kuyu uygulaması', 'Depo ve tank boşaltma', 'Geçici drenaj işleri'],
                'criteria' => ['Suyun temizlik derecesi', 'Daldırma derinliği sınırı', 'Çıkış ağzı çapı', 'Kablo uzunluğu ve şamandıra'],
                'mistake' => 'Genel dalgıç ifadesini her kuyu derinliği veya atık su için uygun kabul etmek, basınç yetersizliği ya da çark tıkanması doğurur.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/temiz-su-dalgic-pompasi', 'label' => 'Temiz su dalgıçları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/kirli-su-dalgic-pompa', 'label' => 'Kirli su dalgıçları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/derin-kuyu-dalgic-pompa', 'label' => 'Derin kuyu dalgıçları']],
            ],
            'su-pompalari/dalgic-pompalar/derin-kuyu-dalgic-pompa' => [
                'hook' => 'Derin kuyu dalgıç pompaları, sondaj içindeki dinamik su seviyesinden yüzeye ve kullanım kotuna yüksek basınçla su çıkarır.',
                'uses' => ['Tarımsal sulama sondajları', 'Kırsal konut su temini', 'Hayvancılık işletmesi beslemesi', 'Depo ve sulama havuzu dolumu'],
                'criteria' => ['4 veya 6 inç kuyu iç çapı', 'Statik ve dinamik su seviyesi', 'Toplam manometrik yükseklik', 'Kuyunun güvenli verimi ve motor gücü'],
                'mistake' => 'Sadece kuyu toplam derinliğini baz almak; dinamik seviye, kot ve boru kayıplarını eklememek yanlış kademe sayısı seçtirir.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/temiz-su-dalgic-pompasi', 'label' => 'Temiz su dalgıç pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/keson-kuyu-pompa', 'label' => 'Keson kuyu pompaları'], ['href' => '/marka/pedrollo', 'label' => 'Pedrollo pompalar']],
                'blog' => ['href' => '/blog/kuyu-dalgic-pompa-secimi-derinlik-rehberi', 'label' => 'Kuyu pompası derinlik rehberi'],
            ],
            'su-pompalari/dalgic-pompalar/drenaj-dalgic-pompa' => [
                'hook' => 'Drenaj dalgıç pompaları, biriken yağmur ve sızıntı suyunu düşük seviyeden hızlıca uzaklaştırmak için geniş debili çalışır.',
                'uses' => ['Bodrum su baskını tahliyesi', 'Kapalı otopark drenaj çukuru', 'İnşaat temelinde su alma', 'Teras ve saha yağmur suyu'],
                'criteria' => ['Tabanda bırakılan minimum su seviyesi', 'İzin verilen partikül çapı', 'Yağışa uygun tahliye debisi', 'Otomatik şamandıranın hareket alanı'],
                'mistake' => 'Şamandırayı dar bir çukurda sıkışacak şekilde bırakmak, pompanın hiç başlamamasına veya susuz çalışmayı sürdürmesine neden olabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/paslanmaz-drenaj-dalgic-pompa', 'label' => 'Paslanmaz drenaj pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/kirli-su-dalgic-pompa', 'label' => 'Kirli su pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/yagmur-suyu-tahliye-pompasi', 'label' => 'Yağmur suyu pompaları']],
                'blog' => ['href' => '/blog/drenaj-pompasi-nedir-nasil-secilir', 'label' => 'Drenaj pompası rehberi'],
            ],
            'su-pompalari/dalgic-pompalar/foseptik-dalgic-pompa' => [
                'hook' => 'Foseptik dalgıç pompalar, atık su çukurlarındaki katı parçacıklı sıvıyı uygun serbest geçişle tahliye eder.',
                'uses' => ['Foseptik kuyusu boşaltma', 'Kanal seviyesine atık su basma', 'Çiftlik sıvı atık transferi', 'Küçük tesis pis su çukuru'],
                'criteria' => ['Serbest katı geçiş çapı', 'Lifli atık için çark tipi', 'Çukur hacmi ve dolum hızı', 'Dikey kot ile yatay hat kaybı'],
                'mistake' => 'Temiz su pompasının yüksek debili görünmesine aldanıp foseptiğe indirmek, dar çark kanallarının kısa sürede kapanmasına yol açar.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/bicakli-dalgic-pompa', 'label' => 'Bıçaklı dalgıç pompalar'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/kirli-su-dalgic-pompa', 'label' => 'Kirli su pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/foseptik-tahliye-cihazi', 'label' => 'Tahliye cihazları']],
                'blog' => ['href' => '/blog/foseptik-dalgic-pompa-secimi-rehberi', 'label' => 'Foseptik pompa seçim rehberi'],
            ],
            'su-pompalari/dalgic-pompalar/karistiricili-camur-pompasi' => [
                'hook' => 'Karıştırıcılı çamur pompaları, çöken tortuyu emiş önünde hareketlendirerek yoğun sıvı-katı karışımının pompaya ulaşmasını kolaylaştırır.',
                'uses' => ['İnşaat çukuru çamuru', 'Kumlu drenaj havuzu', 'Endüstriyel tortu tahliyesi', 'Çökeltim tankı temizliği'],
                'criteria' => ['Katı yoğunluğu ve tane boyutu', 'Karıştırıcı kanadın aşınma dayanımı', 'Motorun çamur özgül ağırlığına uygunluğu', 'Hortum çapı ve tahliye mesafesi'],
                'mistake' => 'Pompa kapasitesini temiz su eğrisinden doğrudan okumak, yoğun çamurda gerçekleşecek debiyi önemli ölçüde yüksek tahmin ettirir.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/kirli-su-dalgic-pompa', 'label' => 'Kirli su pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/drenaj-dalgic-pompa', 'label' => 'Drenaj pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/foseptik-dalgic-pompa', 'label' => 'Foseptik pompaları']],
            ],
            'su-pompalari/dalgic-pompalar/kirli-su-dalgic-pompa' => [
                'hook' => 'Kirli su dalgıç pompaları, yağmur, sızıntı ve hafif atık içindeki belirli büyüklükte parçacıkları tıkanmadan geçirecek hidrolikle üretilir.',
                'uses' => ['Bahçe toplama çukuru', 'Otopark ve bodrum suyu', 'Hafif kirli tank boşaltma', 'Şantiye yüzey suyu'],
                'criteria' => ['Maksimum partikül geçişi', 'Suyun aşındırıcı içeriği', 'Gerekli tahliye süresi', 'Şamandıralı veya manuel işletme'],
                'mistake' => 'Kirli su tanımını yoğun foseptik veya lifli atıkla karıştırmak, pompa serbest geçişi yeterli olsa bile sarılma ve tıkanma yaratabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/drenaj-dalgic-pompa', 'label' => 'Drenaj pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/foseptik-dalgic-pompa', 'label' => 'Foseptik pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/temiz-su-dalgic-pompasi', 'label' => 'Temiz su pompaları']],
            ],
            'su-pompalari/dalgic-pompalar/paslanmaz-drenaj-dalgic-pompa' => [
                'hook' => 'Paslanmaz drenaj dalgıç pompaları, nemli ve hafif korozif ortamlarda gövde dayanımını artırırken kompakt tahliye sağlar.',
                'uses' => ['Gıda alanı yıkama suyu', 'Hafif korozif drenaj', 'Temizliğin önemli olduğu tanklar', 'Deniz etkisine açık servis alanı'],
                'criteria' => ['Paslanmaz çelik kalite sınıfı', 'Conta ve çark malzemesi', 'Sıvının pH ile klor içeriği', 'Partikül boyutu ve sıcaklık'],
                'mistake' => 'Paslanmaz gövdenin her kimyasala dayanacağını varsaymak yanlıştır; elastomer, çark ve salmastra ayrıca uyumlu olmalıdır.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/drenaj-dalgic-pompa', 'label' => 'Drenaj pompaları'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/paslanmaz-pompalar-kimyasal', 'label' => 'Kimyasal pompalar'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/temiz-su-dalgic-pompasi', 'label' => 'Temiz su dalgıçları']],
            ],
            'su-pompalari/dalgic-pompalar/sintine-pompasi' => [
                'hook' => 'Sintine pompaları, tekne veya dar haznelerin tabanında biriken suyu düşük voltajlı ya da kompakt sistemle dışarı atar.',
                'uses' => ['Tekne sintine haznesi', 'Karavan ve mobil sistem drenajı', 'Dar teknik hacim tahliyesi', 'Düşük voltajlı acil su boşaltma'],
                'criteria' => ['12 veya 24 volt besleme', 'Saatlik debi ve basma kotu', 'Otomatik seviye anahtarı', 'Tuzlu suya dayanıklı bağlantı'],
                'mistake' => 'Katalog debisini sıfır basma değerinde okuyup hortum yüksekliği ve dirsekleri hesaba katmamak gerçek tahliyeyi düşürür.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/drenaj-dalgic-pompa', 'label' => 'Drenaj pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/paslanmaz-drenaj-dalgic-pompa', 'label' => 'Paslanmaz drenaj pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/temiz-su-dalgic-pompasi', 'label' => 'Temiz su dalgıçları']],
            ],
            'su-pompalari/dalgic-pompalar/temiz-su-dalgic-pompasi' => [
                'hook' => 'Temiz su dalgıç pompaları, tortusu az kuyu, sarnıç ve depolarda dar geçişli verimli hidrolikle su transfer eder.',
                'uses' => ['Yağmur suyu deposundan sulama', 'Sarnıçtan konut besleme', 'Temiz tank boşaltma', 'Keson kuyudan su alma'],
                'criteria' => ['Suyun kum ve tortu miktarı', 'İstenen minimum emiş seviyesi', 'Basma yüksekliği ile debi', 'İçme suyu malzeme beklentisi'],
                'mistake' => 'Kumlu bir kuyuya temiz su modeli indirmek çark ve yataklarda aşınmayı hızlandırır; kuyu temizliği önce değerlendirilmelidir.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/derin-kuyu-dalgic-pompa', 'label' => 'Derin kuyu pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/kirli-su-dalgic-pompa', 'label' => 'Kirli su pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/keson-kuyu-pompa', 'label' => 'Keson kuyu pompaları']],
            ],
            'su-pompalari/santrifuj-pompalar/paslanmaz-pompalar-kimyasal' => [
                'hook' => 'Paslanmaz kimyasal pompalar, akışkanla temas eden metal yüzeylerde korozyon direnci gereken transfer ve proseslerde kullanılır.',
                'uses' => ['Gıda üretimi temiz su hattı', 'Hafif kimyasal transferi', 'Klorlu havuz yardımcı devresi', 'Pas riski istenmeyen prosesler'],
                'criteria' => ['Akışkanın pH ve konsantrasyonu', 'AISI kalite ve çark malzemesi', 'Salmastra elastomer uyumu', 'Sıcaklık ile viskozite'],
                'mistake' => 'Sadece paslanmaz ibaresine dayanarak solvent veya güçlü asit pompalamak, conta ve salmastrada tehlikeli hasar oluşturabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/santrifuj-pompalar', 'label' => 'Santrifüj pompalar'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/paslanmaz-drenaj-dalgic-pompa', 'label' => 'Paslanmaz drenaj pompaları'], ['href' => '/iletisim', 'label' => 'Teknik iletişim']],
            ],
            'su-pompalari/santrifuj-pompalar/salyangoz-pompalar-bol-su-veren' => [
                'hook' => 'Salyangoz gövdeli bol su pompaları, düşük ve orta basınçta yüksek hacimli akışı geniş hatlara taşımak için tercih edilir.',
                'uses' => ['Salma ve kanal sulama', 'Havuzlar arası su transferi', 'Büyük depo dolumu', 'Düşük kot farkında yüksek debi'],
                'criteria' => ['Yüksek debide gerçek basma ihtiyacı', 'Emiş borusu çapı', 'Pompa devri ve motor gücü', 'Kaplinli veya monoblok yapı'],
                'mistake' => 'Yüksek debili pompayı dar boruya bağlamak sürtünme kaybını büyütür; motor gücü artsa da uçtaki su beklenen seviyeye çıkmaz.',
                'related' => [['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/santrifuj-pompalar-sulama', 'label' => 'Sulama pompaları'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/tek-fanli-santrifuj-pompa', 'label' => 'Tek fanlı pompalar'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/dizel-su-motorlari', 'label' => 'Dizel su motorları']],
            ],
            'su-pompalari/santrifuj-pompalar/santrifuj-pompalar-sulama' => [
                'hook' => 'Sulama santrifüj pompaları, kaynaktaki suyu tarla veya bahçe dağıtım hattının istediği debi ve basınca taşır.',
                'uses' => ['Damla sulama ana hattı', 'Yağmurlama sistemi beslemesi', 'Bahçe hortumu ve sprinkler', 'Tarla kanalından su çekme'],
                'criteria' => ['Sulama zonlarının toplam debisi', 'En uzak noktadaki gerekli basınç', 'Emiş seviyesi ve su kaynağı', 'Filtre ile boru kayıpları'],
                'mistake' => 'Tüm zonları aynı anda açık varsaymadan pompa seçmek veya filtre kaybını atlamak, uzak laterallerde düzensiz sulamaya neden olur.',
                'related' => [['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/salyangoz-pompalar-bol-su-veren', 'label' => 'Bol su veren pompalar'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/derin-kuyu-dalgic-pompa', 'label' => 'Derin kuyu pompaları'], ['href' => '/pompa-secici', 'label' => 'Pompa Seçici']],
            ],
            'su-pompalari/santrifuj-pompalar/tek-fanli-santrifuj-pompa' => [
                'hook' => 'Tek fanlı santrifüj pompalar, genel su transferinde sade hidrolik, dengeli debi ve kolay bakım sunar.',
                'uses' => ['Bahçe ve küçük tarla sulama', 'Depo dolum-boşaltım', 'Tek kat tesisat beslemesi', 'Makine soğutma suyu'],
                'criteria' => ['Orta basınçtaki görev noktası', 'Fan çapı ve motor devri', 'Emiş ağzı ile boru çapı', 'Monofaze veya trifaze motor'],
                'mistake' => 'Yüksek kat veya uzun basınç hattında tek fanlı modeli zorlamak, vanayı kısarak enerji kaybı yaratmaya ve düşük debiye yol açar.',
                'related' => [['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/cift-fanli-santrifuj-pompa', 'label' => 'Çift fanlı pompalar'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/santrifuj-pompalar-sulama', 'label' => 'Sulama pompaları'], ['href' => '/kategoriler/su-pompalari/preferikal-pompalar-surtme-fanli', 'label' => 'Periferik pompalar']],
            ],
            'su-pompalari/santrifuj-pompalar/cift-fanli-santrifuj-pompa' => [
                'hook' => 'Çift fanlı santrifüj pompalar, iki çark kademesiyle tek fanlı modellere göre daha yüksek basınç üretir.',
                'uses' => ['Çok katlı bina su beslemesi', 'Uzun yağmurlama hatları', 'Yüksek kotlu depo dolumu', 'Basınç isteyen yıkama hattı'],
                'criteria' => ['Hedef basınçta kalan debi', 'İki kademenin verim aralığı', 'Motor gücü ve faz tipi', 'Mekanik salmastra çalışma koşulu'],
                'mistake' => 'Çift fanın her zaman iki kat debi vereceğini düşünmek yanlıştır; temel kazanım çoğunlukla basma yüksekliğindedir.',
                'related' => [['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/tek-fanli-santrifuj-pompa', 'label' => 'Tek fanlı pompalar'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar', 'label' => 'Kademeli pompalar'], ['href' => '/kategoriler/hidrofor-sistemleri/hidroforlar', 'label' => 'Hidroforlar']],
            ],
            'su-pompalari/ozel-amacli-pompalar/dizel-su-motorlari' => [
                'hook' => 'Dizel su motorları, elektrik altyapısının bulunmadığı arazide sulama ve yüksek hacimli transfer için bağımsız güç sağlar.',
                'uses' => ['Elektriksiz tarla sulama', 'Kanal ve göletten su çekme', 'Şantiye acil drenajı', 'Mobil depo dolumu'],
                'criteria' => ['Pompa debisiyle motor gücü eşleşmesi', 'Yakıt tüketimi ve depo süresi', 'Manuel veya marşlı çalıştırma', 'Şase, hortum ve taşınabilirlik'],
                'mistake' => 'Motorun azami gücünü sürekli güç kabul etmek aşırı yük, yüksek yakıt tüketimi ve erken motor aşınması yaratabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/salyangoz-pompalar-bol-su-veren', 'label' => 'Bol su pompaları'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/santrifuj-pompalar-sulama', 'label' => 'Sulama pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/yangin-pompalari', 'label' => 'Yangın pompaları']],
            ],
            'su-pompalari/ozel-amacli-pompalar/foseptik-tahliye-cihazi' => [
                'hook' => 'Foseptik tahliye cihazları, yerçekimiyle kanalizasyona ulaşamayan atık suyu kapalı hazne ve otomatik pompayla üst kota taşır.',
                'uses' => ['Bodrum kattaki tuvalet', 'Kanal seviyesinin altındaki lavabo', 'Ek yapı atık su bağlantısı', 'Küçük işletme hijyen hacmi'],
                'criteria' => ['Bağlanacak armatür sayısı', 'Katı öğütme veya serbest geçiş', 'Dikey ve yatay basma mesafesi', 'Hazne hacmi ile havalandırma'],
                'mistake' => 'Cihazı izin verilmeyen sıcak suya, kimyasala veya çok sayıda armatüre bağlamak taşma ve motor arızası riski doğurur.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/foseptik-dalgic-pompa', 'label' => 'Foseptik dalgıç pompalar'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/bicakli-dalgic-pompa', 'label' => 'Bıçaklı dalgıç pompalar'], ['href' => '/iletisim', 'label' => 'Teknik destek']],
            ],
            'su-pompalari/ozel-amacli-pompalar/jakuzi-pompasi' => [
                'hook' => 'Jakuzi pompaları, spa kabinindeki jetlere konforlu masaj etkisi verecek sürekli ve sessiz su dolaşımını sağlar.',
                'uses' => ['Ev tipi jakuzi jetleri', 'Spa masaj devresi', 'Küçük wellness havuzu', 'Kabin içi su sirkülasyonu'],
                'criteria' => ['Jet sayısı ve toplam debi', 'Bağlantı ölçüsü ile mevcut tesisat', 'Sessizlik ve titreşim seviyesi', 'Su sıcaklığına dayanım'],
                'mistake' => 'Yalnız motor gücünü eşleştirip bağlantı çapı ile pompa eğrisini atlamak zayıf jet etkisi veya aşırı gürültü oluşturur.',
                'related' => [['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/on-filtreli-havuz-pompasi', 'label' => 'Ön filtreli havuz pompaları'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari', 'label' => 'Sirkülasyon pompaları'], ['href' => '/iletisim', 'label' => 'Ürün danışmanlığı']],
            ],
            'su-pompalari/ozel-amacli-pompalar/keson-kuyu-pompa' => [
                'hook' => 'Keson kuyu pompaları, geniş çaplı ve görece sığ kuyularda değişken su seviyesine uygun biçimde su temin eder.',
                'uses' => ['Taş örme keson kuyular', 'Bahçe sulama suyu', 'Kırsal konut deposu dolumu', 'Sarnıç benzeri geniş kaynaklar'],
                'criteria' => ['Dinamik su seviyesi', 'Kuyudaki tortu miktarı', 'Pompanın soğutma biçimi', 'Askı, kablo ve çıkış borusu'],
                'mistake' => 'Keson kuyu ile dar sondaj kuyusunu aynı kabul etmek, motor soğutması ve gövde çapında uygunsuz seçim doğurabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/derin-kuyu-dalgic-pompa', 'label' => 'Derin kuyu pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/temiz-su-dalgic-pompasi', 'label' => 'Temiz su dalgıçları'], ['href' => '/kategoriler/su-pompalari/jet-pompalar-derinden-emisli', 'label' => 'Jet pompalar']],
            ],
            'su-pompalari/ozel-amacli-pompalar/klapeli-pompalar' => [
                'hook' => 'Klapeli pompalar, valf kontrollü akış yapısıyla belirli transfer ve tahliye işlerinde geri kaçışı sınırlayan özel çözümlerdir.',
                'uses' => ['Kesintili su transferi', 'Kendinden emiş gereken işler', 'Küçük saha tahliyesi', 'Basit tarımsal uygulamalar'],
                'criteria' => ['Klapenin partikül ve sıvıyla uyumu', 'Emiş yüksekliği', 'Darbeli akışın tesisata etkisi', 'Bakımda valfe erişim'],
                'mistake' => 'Klapenin katı maddeyi sınırsız geçireceğini varsaymak, valfin açık kalmasına ve pompanın emişini kaybetmesine neden olabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/jet-pompalar-derinden-emisli', 'label' => 'Jet pompalar'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar', 'label' => 'Santrifüj pompalar'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar', 'label' => 'Özel amaçlı pompalar']],
            ],
            'su-pompalari/ozel-amacli-pompalar/yangin-pompalari' => [
                'hook' => 'Yangın pompaları, sprinkler, hidrant ve dolap hatlarında projede belirlenen acil durum debi-basıncını güvenilir biçimde sağlar.',
                'uses' => ['Sprinkler ana beslemesi', 'Yangın dolabı hattı', 'Açık alan hidrant sistemi', 'Jockey basınç koruma devresi'],
                'criteria' => ['Onaylı hidrolik proje noktası', 'Elektrikli ve dizel yedeklilik', 'Jockey pompa kapasitesi', 'Pano, test hattı ve standart uygunluğu'],
                'mistake' => 'Konut hidroforunu yangın pompası yerine kullanmak proje, dayanım ve otomasyon gerekliliklerini karşılamaz; can güvenliği riski doğurur.',
                'related' => [['href' => '/kategoriler/hidrofor-sistemleri/hidrofor-grubu', 'label' => 'Hidrofor grupları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/dizel-su-motorlari', 'label' => 'Dizel su motorları'], ['href' => '/iletisim', 'label' => 'Proje teklifi']],
                'blog' => ['href' => '/blog/yangin-pompasi-nedir-nasil-secilir', 'label' => 'Yangın pompası teknik rehberi'],
            ],
            'su-pompalari/ozel-amacli-pompalar/yagmur-suyu-tahliye-pompasi' => [
                'hook' => 'Yağmur suyu tahliye pompaları, ani yağışta toplama çukuru veya saha drenajında biriken suyu taşma olmadan uzaklaştırır.',
                'uses' => ['Otopark rampası drenajı', 'Teras ve avlu toplama çukuru', 'Alt geçit ile bodrum koruması', 'Yağmur suyu deposu aktarımı'],
                'criteria' => ['Havza alanı ve tasarım yağış şiddeti', 'Çukurun faydalı hacmi', 'Tek veya yedekli pompa düzeni', 'Seviye sensörü ve alarm'],
                'mistake' => 'Ortalama yağışa göre kapasite seçmek kısa süreli sağanakta çukurun pompadan hızlı dolmasına ve taşmasına neden olabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/dalgic-pompalar/drenaj-dalgic-pompa', 'label' => 'Drenaj dalgıç pompaları'], ['href' => '/kategoriler/su-pompalari/dalgic-pompalar/kirli-su-dalgic-pompa', 'label' => 'Kirli su pompaları'], ['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar', 'label' => 'Özel amaçlı pompalar']],
            ],
            'su-pompalari/ozel-amacli-pompalar/on-filtreli-havuz-pompasi' => [
                'hook' => 'Ön filtreli havuz pompaları, suyu filtre tesisatında dolaştırırken sepetiyle yaprak ve iri parçaları çarktan önce tutar.',
                'uses' => ['Özel yüzme havuzu filtrasyonu', 'Site havuzu devridaimi', 'Süs havuzu filtre hattı', 'Havuz ısıtıcı beslemesi'],
                'criteria' => ['Havuz hacmi ve günlük çevrim süresi', 'Filtre basınç kaybı', 'Klor veya tuzlu su malzeme uyumu', 'Kendinden emiş ve ön filtre hacmi'],
                'mistake' => 'Debiyi yalnız havuz hacmine göre hesaplayıp filtre, ısıtıcı ve boru kayıplarını dışarıda bırakmak yetersiz çevrim yaratır.',
                'related' => [['href' => '/kategoriler/su-pompalari/ozel-amacli-pompalar/jakuzi-pompasi', 'label' => 'Jakuzi pompaları'], ['href' => '/kategoriler/su-pompalari/santrifuj-pompalar/paslanmaz-pompalar-kimyasal', 'label' => 'Paslanmaz pompalar'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari', 'label' => 'Sirkülasyon pompaları']],
            ],
            'su-pompalari/kademeli-pompalar/dikey-kademeli-pompalar' => [
                'hook' => 'Dikey kademeli pompalar, üst üste dizilen çarklarla dar taban alanında yüksek basınçlı ve verimli su transferi sağlar.',
                'uses' => ['Bina hidrofor grupları', 'Ters osmoz besleme hattı', 'Endüstriyel yıkama sistemi', 'Kazan besleme uygulaması'],
                'criteria' => ['Kademe sayısı ile görev basıncı', 'Giriş basıncı ve kavitasyon payı', 'Paslanmaz hidrolik malzeme', 'Dikey servis yüksekliği'],
                'mistake' => 'Pompanın üzerinde bakım için yeterli sökme mesafesi bırakmamak, mekanik salmastra ve kademe servislerini zorlaştırır.',
                'related' => [['href' => '/kategoriler/su-pompalari/kademeli-pompalar/yatay-kademeli-pompalar', 'label' => 'Yatay kademeli pompalar'], ['href' => '/kategoriler/hidrofor-sistemleri/hidrofor-grubu', 'label' => 'Hidrofor grupları'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar', 'label' => 'Kademeli pompalar']],
            ],
            'su-pompalari/kademeli-pompalar/monoblok-yatay-kademeli' => [
                'hook' => 'Monoblok yatay kademeli pompalar, motor ve pompayı ortak kompakt gövdede birleştirerek yüksek basıncı kolay kurulumla sunar.',
                'uses' => ['Kompakt hidrofor paketleri', 'Bahçe yağmurlama hattı', 'Küçük proses basınçlandırması', 'Depodan uzun hat besleme'],
                'criteria' => ['Kompakt gövdenin görev eğrisi', 'Emiş koşulu ve ilk dolum', 'Kademe malzemesi', 'Motor soğutma boşluğu'],
                'mistake' => 'Monoblok yapıyı hizalama gerektirmez diye gerilimli boruya bağlamak, gövde ve salmastra üzerinde mekanik yük oluşturur.',
                'related' => [['href' => '/kategoriler/su-pompalari/kademeli-pompalar/yatay-kademeli-pompalar', 'label' => 'Yatay kademeli pompalar'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar/norm-tipi-yatay-kademeli', 'label' => 'Norm tipi kademeli pompalar'], ['href' => '/kategoriler/hidrofor-sistemleri/hidroforlar', 'label' => 'Hidroforlar']],
            ],
            'su-pompalari/kademeli-pompalar/norm-tipi-yatay-kademeli' => [
                'hook' => 'Norm tipi yatay kademeli pompalar, kaplinli ve servis edilebilir yapısıyla yüksek basınçlı endüstriyel görevlerde esneklik sağlar.',
                'uses' => ['Büyük bina basınç sistemleri', 'Endüstriyel proses transferi', 'Uzun mesafe su iletimi', 'Yüksek basınçlı sulama'],
                'criteria' => ['Norm standardı ve bağlantı ölçüleri', 'Kaplin-hizalama düzeni', 'Yataklama ile eksenel yük', 'Motorun ayrı seçilen gücü'],
                'mistake' => 'Şase ve kaplin hizasını sıcak çalışma sonrası kontrol etmemek titreşim, rulman ısınması ve salmastra kaçağına yol açabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/kademeli-pompalar/monoblok-yatay-kademeli', 'label' => 'Monoblok yatay pompalar'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar/yatay-kademeli-pompalar', 'label' => 'Yatay kademeli pompalar'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar/dikey-kademeli-pompalar', 'label' => 'Dikey kademeli pompalar']],
            ],
            'su-pompalari/kademeli-pompalar/yatay-kademeli-pompalar' => [
                'hook' => 'Yatay kademeli pompalar, birden fazla çarkla yüksek basınç üretirken zeminden erişilen bakım düzeni sunar.',
                'uses' => ['Yüksek kotlu depo besleme', 'Basınçlı yıkama hattı', 'Sulama ana borusu', 'Konut ve tesis hidroforu'],
                'criteria' => ['Debide gerekli toplam kademe', 'Zemin alanı ve servis erişimi', 'Emiş tarafı basınç koşulu', 'Gövde ile çark malzemesi'],
                'mistake' => 'Emiş borusunu pompa ağzından küçük seçmek ilk kademede kavitasyon yaratıp tüm kademelerin performansını düşürebilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/kademeli-pompalar/dikey-kademeli-pompalar', 'label' => 'Dikey kademeli pompalar'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar/monoblok-yatay-kademeli', 'label' => 'Monoblok yatay pompalar'], ['href' => '/kategoriler/su-pompalari/kademeli-pompalar/norm-tipi-yatay-kademeli', 'label' => 'Norm tipi pompalar']],
            ],
            'su-pompalari/sirkulasyon-pompalari/flansli-sirkulasyon-pompalari' => [
                'hook' => 'Flanşlı sirkülasyon pompaları, daha büyük boru çapı ve debiye sahip ısıtma-soğutma devrelerine sağlam bağlantı sunar.',
                'uses' => ['Apartman merkezi ısıtması', 'Ticari bina klima devresi', 'Kazan dairesi ana kollektörü', 'Endüstriyel sıcak su çevrimi'],
                'criteria' => ['Flanş çapı ve basınç sınıfı', 'Tesisat debisi ile yük kaybı', 'Tekli veya ikiz pompa ihtiyacı', 'Değişken devir kontrolü'],
                'mistake' => 'Mevcut flanş çapı uyuyor diye pompa eğrisini kontrol etmeden değişim yapmak balanssız debi ve yüksek elektrik tüketimi oluşturabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/inline-sirkulasyon-pompalari', 'label' => 'Inline sirkülasyon pompaları'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/rekorlu-disli-sirkulasyon-pompalari', 'label' => 'Rekorlu pompalar'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari', 'label' => 'Sirkülasyon pompaları']],
            ],
            'su-pompalari/sirkulasyon-pompalari/inline-sirkulasyon-pompalari' => [
                'hook' => 'Inline sirkülasyon pompaları, emiş ve basma ağızları aynı eksende olduğundan boru hattına kompakt biçimde yerleşir.',
                'uses' => ['Dar kazan dairesi hatları', 'Ticari HVAC çevrimi', 'Kule ve eşanjör devresi', 'Bina ana dağıtım kolu'],
                'criteria' => ['Hat çapı ve yüz yüze montaj boyu', 'Motorun kuru kalacağı yön', 'Sistem basıncı ile sıcaklığı', 'Değişken debide kontrol yöntemi'],
                'mistake' => 'Motor milini uygun olmayan yönde monte etmek rulman yağlamasını ve hava tahliyesini bozarak sesli çalışmaya neden olabilir.',
                'related' => [['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/flansli-sirkulasyon-pompalari', 'label' => 'Flanşlı pompalar'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/rekorlu-disli-sirkulasyon-pompalari', 'label' => 'Rekorlu pompalar'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari', 'label' => 'Sirkülasyon pompaları']],
            ],
            'su-pompalari/sirkulasyon-pompalari/rekorlu-disli-sirkulasyon-pompalari' => [
                'hook' => 'Rekorlu dişli sirkülasyon pompaları, küçük ve orta çaplı konut ısıtma devrelerinde hızlı değişim ve kompakt bağlantı sağlar.',
                'uses' => ['Kombi ve kazan dönüş hattı', 'Yerden ısıtma kollektörü', 'Küçük bina kalorifer devresi', 'Boyler serpantin çevrimi'],
                'criteria' => ['Rekor ölçüsü ve montaj boyu', 'Kademe veya elektronik kontrol', 'Tesisat direnci', 'Akışkan sıcaklık sınırı'],
                'mistake' => 'Eski pompanın yalnız bağlantı ölçüsünü eşleştirmek, yeni modelin basma yüksekliği farklıysa tesisatta uğultu veya yetersiz ısınma yaratır.',
                'related' => [['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/flansli-sirkulasyon-pompalari', 'label' => 'Flanşlı pompalar'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/sicak-su-pompalari', 'label' => 'Sıcak su pompaları'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari', 'label' => 'Sirkülasyon pompaları']],
            ],
            'su-pompalari/sirkulasyon-pompalari/sicak-su-pompalari' => [
                'hook' => 'Sıcak su sirkülasyon pompaları, uzun tesisatta dönüş hattını canlı tutarak muslukta bekleme süresini ve boşa akan suyu azaltır.',
                'uses' => ['Villa kullanım sıcak suyu dönüşü', 'Otel oda hatları', 'Restoran ve spor tesisi', 'Boyler ile uzak musluk çevrimi'],
                'criteria' => ['Dönüş hattı uzunluğu', 'Kullanım suyu için gövde uygunluğu', 'Sıcaklık ve kireç koşulu', 'Zamanlayıcı veya sıcaklık kontrolü'],
                'mistake' => 'Bu pompayı hidrofor gibi basınç artırmak için seçmek sorunu çözmez; görevi kapalı dönüş hattında dolaşım sağlamaktır.',
                'related' => [['href' => '/kategoriler/hidrofor-sistemleri/sicak-su-hidroforu', 'label' => 'Sıcak su hidroforları'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari/rekorlu-disli-sirkulasyon-pompalari', 'label' => 'Rekorlu sirkülasyon pompaları'], ['href' => '/kategoriler/su-pompalari/sirkulasyon-pompalari', 'label' => 'Sirkülasyon pompaları']],
                'blog' => ['href' => '/blog/sicak-su-sirkulasyon-pompasi-secimi', 'label' => 'Sıcak su sirkülasyonu rehberi'],
            ],

            // --- Isıtma sistemleri / Ardonat elektrikli ısıtıcılar ---
            'isitma-sistemleri' => [
                'hook' => 'Isıtma sistemleri; açık, yarı açık ve kapalı alanlarda lokal veya bölgesel konfor sağlayan elektrikli infrared ve panel ısıtma çözümlerini kapsar.',
                'uses' => ['Kafe ve restoran terası', 'Ev balkonu ve oturma odası', 'Otel veranda ve bahçe', 'Ofis, showroom ve atölye lokal ısıtma'],
                'criteria' => ['Açık, yarı açık veya kapalı alan ayrımı', 'Montaj tipi: duvar, dikey tower veya panel', 'Güç (W) ve ısıtılacak lokal alan', 'Kumanda / kademe ve güvenlik özellikleri'],
                'mistake' => 'Kombi veya kalorifer sirkülasyon pompası ihtiyacını elektrikli infrared ısıtıcıyla karıştırmak; ya da açık alan için iç mekân panel seçmek hem güvenlik hem performans kaybı yaratır.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar', 'label' => 'Elektrikli ısıtıcılar'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar', 'label' => 'Dış mekân ısıtıcılar'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar', 'label' => 'Ev tipi ısıtıcılar'],
                    ['href' => '/marka/ardonat', 'label' => 'Ardonat markası'],
                ],
                'brands_note' => 'Ardonat Halogen Black, Tower, Twin ve iç mekân serileri; montaj tipi ve güç ihtiyacına göre karşılaştırılır.',
                'table' => [
                    ['Dış mekân infrared', 'Teras, kafe, restoran', 'Rüzgârlı alanda lokal ısı'],
                    ['Dikey tower', 'Balkon, veranda, ev', 'Zemin alanı kaplamadan dikey ısı'],
                    ['Panel / iç mekân', 'Oda ve ofis', 'Sessiz ve homojen ısı'],
                ],
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
            'isitma-sistemleri/elektrikli-isiticilar' => [
                'hook' => 'Elektrikli ısıtıcılar, kızılötesi (infrared/halojen) veya panel teknolojisiyle hedef bölgeyi hızlı ısıtır; tesisat kazını gerektirmeden kurulum sağlar.',
                'uses' => ['Dış mekân kafe ve restoran ısıtması', 'Ev tipi oda ve balkon konforu', 'Geçici veya sezonluk lokal ısıtma', 'Yüksek tavanlı mekânlarda noktasal ısı'],
                'criteria' => ['İç / dış mekân uygunluğu', 'Watt gücü ve kademe kontrolü', 'Duvar, tavan veya dikey montaj', 'IP koruma ve güvenlik sensörleri'],
                'mistake' => 'Yalnız watt değerine bakıp alanın açık/kapalı oluşunu ve montaj yüksekliğini yok saymak; gereğinden büyük cihaz hem elektrik hem konfor kaybı üretir.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar', 'label' => 'Dış mekân ısıtıcılar'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar', 'label' => 'Ev tipi ısıtıcılar'],
                    ['href' => '/marka/ardonat', 'label' => 'Ardonat ısıtıcılar'],
                ],
                'brands_note' => 'Ardonat infrared serileri dış mekân ve ev tipi ihtiyaçlara göre ayrılır; model seçiminde kullanım senaryosu önceliklidir.',
                'table' => [
                    ['Duvar tipi', 'Sabit teras / oda', 'Yer kaplamaz'],
                    ['Dikey tower', 'Esnek konum', 'Taşınabilir veya sabit dikey'],
                    ['Panel', 'İç mekân', 'Düşük gürültü'],
                ],
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
            'isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar' => [
                'hook' => 'Dış mekân ısıtıcılar; teras, bahçe, kafe ve restoran gibi açık veya yarı açık alanlarda infrared ısı ile lokal konfor sağlar.',
                'uses' => ['Kafe ve restoran terası', 'Otel bahçe ve veranda', 'Açık oturma alanları', 'Showroom önü yarı açık mekânlar'],
                'criteria' => ['Rüzgâr ve yağmura kısmi maruziyet', 'Duvar veya dikey tower montajı', '2000–4000 W güç aralığı', 'Uzaktan kumanda ve kademe ihtiyacı'],
                'mistake' => 'İç mekân panel ısıtıcıyı açık terasa kurmak veya tek 2000 W cihazla geniş rüzgârlı alanı ısıtmaya çalışmak beklenen konforu vermez.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar/duvar-tipi-dis-mekan-isiticilar', 'label' => 'Duvar tipi dış mekân'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar/dikey-tower-dis-mekan-isiticilar', 'label' => 'Dikey tower dış mekân'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar', 'label' => 'Ev tipi ısıtıcılar'],
                ],
                'brands_note' => 'Ardonat Halogen Black ve Tower dış mekân serileri; güç, Twin yapı ve kumanda seçenekleriyle ayrılır.',
                'table' => [
                    ['Halogen Black', 'Duvar / yatay', 'Kafe terası'],
                    ['Halogen Tower', 'Dikey', 'Veranda ve balkon'],
                    ['Twin seriler', 'Geniş alan', 'Çift lamba yüksek güç'],
                ],
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
            'isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar/duvar-tipi-dis-mekan-isiticilar' => [
                'hook' => 'Duvar tipi dış mekân ısıtıcılar, yatay montajla teras ve kafe alanlarında yer kaplamadan infrared ısı dağıtır.',
                'uses' => ['Restoran duvar montajı', 'Kafe saçak altı', 'Otel teras kenarı', 'Mağaza vitrin önü yarı açık alan'],
                'criteria' => ['Montaj yüksekliği ve açı', '2000–4000 W güç', 'Pro / kumandalı kademe ihtiyacı', 'Gövde uzunluğu ve ısıtma şeridi'],
                'mistake' => 'Çok alçak montajla oturma bölgesine doğrudan yakın kurulum; güvenlik mesafesini ve ısı dağılımını bozar.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar/dikey-tower-dis-mekan-isiticilar', 'label' => 'Dikey tower modeller'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar', 'label' => 'Tüm dış mekân ısıtıcılar'],
                    ['href' => '/marka/ardonat', 'label' => 'Ardonat'],
                ],
                'brands_note' => 'Ardonat Halogen Black, Black Pro, Plus, Twin ve Twin Pro duvar tipi dış mekân serisinin ana modelleridir.',
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
            'isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar/dikey-tower-dis-mekan-isiticilar' => [
                'hook' => 'Dikey tower dış mekân ısıtıcılar, ayakta veya sabit dikey formda infrared ısı vererek balkon, veranda ve yarı açık alanlarda esnek konumlandırma sunar.',
                'uses' => ['Kafe veranda köşeleri', 'Otel bahçe oturma grubu', 'Yarı açık event alanları', 'Taşınabilir ihtiyaçlı işletmeler'],
                'criteria' => ['Tek veya Twin lamba gücü', 'Aç-kapa veya 5 kademe kumanda', 'Devrilme emniyeti', 'İç / yarı açık kullanım sınırı'],
                'mistake' => 'Tower modeli tamamen açık ve rüzgârlı alanda duvar tipi kadar geniş bir şeridi tek başına ısıtacağını varsaymak yanlış boyutlandırmaya yol açar.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar/duvar-tipi-dis-mekan-isiticilar', 'label' => 'Duvar tipi dış mekân'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/dikey-ev-tipi-isiticilar', 'label' => 'Dikey ev tipi ısıtıcılar'],
                    ['href' => '/marka/ardonat', 'label' => 'Ardonat'],
                ],
                'brands_note' => 'Ardonat Halogen Tower, Tower Pro ve Tower Twin modelleri dikey dış / yarı açık kullanım için öne çıkar.',
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
            'isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar' => [
                'hook' => 'Ev tipi elektrikli ısıtıcılar; oda, balkon, ofis ve küçük yaşam alanlarında hızlı, sessiz ve kurulumu kolay lokal ısıtma sağlar.',
                'uses' => ['Oturma odası ve çalışma odası', 'Kapalı balkon', 'Ev ofisi', 'Misafir odası sezonluk takviye ısı'],
                'criteria' => ['Oda metrekare ve tavan yüksekliği', 'Dikey tower, duvar veya panel tercihi', 'Gürültü ve çocuk/evcil güvenlik', 'Kademe ve termostat ihtiyacı'],
                'mistake' => 'Kafe terası için tasarlanmış yüksek güçlü dış mekân cihazını küçük kapalı odada sürekli çalıştırmak hem elektrik tüketimini hem güvenlik riskini artırır.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/dikey-ev-tipi-isiticilar', 'label' => 'Dikey ev tipi'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/duvar-tipi-ev-isiticilar', 'label' => 'Duvar tipi ev'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/panel-isiticilar', 'label' => 'Panel ısıtıcılar'],
                ],
                'brands_note' => 'Ardonat Tower, Step Carbon / Micatronic ve panel serileri ev tipi senaryolara göre seçilir.',
                'table' => [
                    ['Dikey tower', 'Oda / balkon', 'Hızlı infrared'],
                    ['Duvar tipi ev', 'Sabit oda montajı', 'Yer tasarrufu'],
                    ['Panel', 'Sürekli iç mekân', 'Homojen ısı'],
                ],
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
            'isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/dikey-ev-tipi-isiticilar' => [
                'hook' => 'Dikey ev tipi ısıtıcılar, tower formunda infrared ısı ile oda ve kapalı balkonda hızlı ısınma sunar; zemin alanı kaplamadan dikey konumlanır.',
                'uses' => ['Salon ve çalışma odası', 'Kapalı balkon', 'Ev ofisi', 'Geçici ekstra ısı ihtiyacı'],
                'criteria' => ['1500–3000 W güç seçimi', 'Kumandalı kademe tercihi', 'Devrilme emniyeti', 'İç mekân kullanım onayı'],
                'mistake' => 'Cihazı perdenin arkasına veya yanıcı malzemeye çok yakın yerleştirmek; üretici güvenlik mesafesini yok saymak risk oluşturur.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/duvar-tipi-ev-isiticilar', 'label' => 'Duvar tipi ev ısıtıcılar'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/panel-isiticilar', 'label' => 'Panel ısıtıcılar'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/dis-mekan-isiticilar/dikey-tower-dis-mekan-isiticilar', 'label' => 'Dış mekân tower'],
                ],
                'brands_note' => 'Ardonat Halogen Tower ve Tower Pro ev / yarı açık balkon kullanımında dikey formun temel seçenekleridir.',
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
            'isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/duvar-tipi-ev-isiticilar' => [
                'hook' => 'Duvar tipi ev ısıtıcılar, sabit montajla odada yer kaplamadan infrared veya karbon ısı dağıtır.',
                'uses' => ['Oturma odası duvar montajı', 'Koridor ve giriş holü', 'Küçük ofis', 'Yatay veya dik montajlı iç mekân modeller'],
                'criteria' => ['Montaj duvarı taşıyıcılığı', 'Güç ve ısıtma alanı (m²)', 'Kumanda / kademe', 'İç mekân IP ve güvenlik'],
                'mistake' => 'Dış mekân IP odaklı yüksek güçlü Black serisini küçük yatak odasına kurup sürekli tam güçte çalıştırmak konfor ve tüketim dengesini bozar.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/dikey-ev-tipi-isiticilar', 'label' => 'Dikey ev tipi'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/panel-isiticilar', 'label' => 'Panel ısıtıcılar'],
                    ['href' => '/marka/ardonat', 'label' => 'Ardonat'],
                ],
                'brands_note' => 'Ardonat Step Carbon / Micatronic ve uygun güçteki duvar tipi modeller iç mekân duvar montajı için değerlendirilir.',
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
            'isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/panel-isiticilar' => [
                'hook' => 'Panel ısıtıcılar, geniş yüzey üzerinden homojen ısı yayarak oda ve ofiste sessiz iç mekân ısınması sağlar.',
                'uses' => ['Oturma ve yatak odası', 'Ofis ve toplantı alanı', '15–25 m² iç mekân takviye ısı', 'Sürekli kullanım senaryoları'],
                'criteria' => ['Panel ölçüleri (ör. 600x600 / 600x1200)', '1000–2500 W güç', 'Montaj yüksekliği', 'Termostat veya kademe kontrolü'],
                'mistake' => 'Panel ısıtıcıyı açık teras veya rüzgârlı dış mekânda ana ısı kaynağı sanmak; panel teknolojisi iç mekân homojen ısıya yöneliktir.',
                'related' => [
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar', 'label' => 'Ev tipi ısıtıcılar'],
                    ['href' => '/kategoriler/isitma-sistemleri/elektrikli-isiticilar/ev-tipi-isiticilar/dikey-ev-tipi-isiticilar', 'label' => 'Dikey ev tipi'],
                    ['href' => '/marka/ardonat', 'label' => 'Ardonat'],
                ],
                'brands_note' => 'Ardonat panel ısıtıcı modelleri iç mekân m² ve panel ölçüsüne göre seçilir.',
                'closing' => $heaterClosing,
                'guide_closing' => $heaterGuideClosing,
            ],
        ];
    }

    /** @return array<string, mixed>|null */
    public static function forPath(string $path): ?array
    {
        return self::all()[trim($path, '/')] ?? null;
    }
}
